"""Derived dashboard read models for the execution telemetry spine — facade over the split modules.

This module reads migration-037 telemetry tables and returns JSON-friendly
models for dashboard/reporting callers. The read models are intentionally
derived views: they do not mutate SQLite and they are not workflow authority.

WO-GF-TELEMETRY-SPLIT: implementation moved to read_models_{shared,modules,
security,outcomes,tokens,validation,components,timeline,summary}.py; this
module re-exports the full prior public+private surface so existing
`from core.telemetry.read_models import X` callers are unchanged.
"""

from __future__ import annotations

from .read_models_components import (
    _DUCKDB_COMPONENT_EVENT_TYPES,
    _component_drilldowns,
    _component_hardening_intelligence,
    _component_usage,
    _component_usage_from_events_fact,
    _component_usage_rows,
    _drilldown_entry_points,
    _entity_drilldowns,
    _process_run_drilldowns,
    _source_tables_for_components,
    component_usage_summary,
)
from .read_models_modules import (
    MODULE_SEGMENTS,
    dashboard_module_read_models,
    dashboard_module_segments,
)
from .read_models_outcomes import (
    _attention_groups,
    _attention_rollup,
    _outcome_rollup,
    _research_decision_rollup,
    _route_explainability,
    _route_rollup,
    dashboard_attention_summary,
)
from .read_models_security import (
    _security_attribution,
    _security_remediation_intelligence,
    _security_rollup,
    _security_status_counts,
)
from .read_models_shared import (
    COMPONENT_TABLES,
    CORE_TABLES,
    FACT_TABLES,
    ScopeFilter,
    _ATTENTION_EVENTS_VIEW_SQL,
    _DECISION_EVENTS_VIEW_SQL,
    _OUTCOME_EVENTS_VIEW_SQL,
    _add_condition,
    _analytics_rows,
    _connect,
    _distinct_count,
    _entity_counts,
    _first,
    _json_list,
    _json_object,
    _none_if_unknown,
    _outcome_row_count,
    _process_runs_from_events,
    _require_tables,
    _row_count,
    _rows,
    _scope_dict,
    _scope_from_rollup_row,
    _scoped_rows,
    _scoped_rows_from_sql,
    _security_finding_row_count,
    _table_counts,
    _where_scope,
    _where_scope_project_only,
    _with_authority,
)
from .read_models_summary import (
    _scoped_summary,
    global_telemetry_summary,
    milestone_telemetry_summary,
    project_telemetry_summary,
    task_telemetry_summary,
)
from .read_models_timeline import process_run_timeline, workflow_execution_graph
from .read_models_tokens import (
    _REPORTABLE_COST_VISIBILITIES,
    _TOKEN_ROLLUP_DIM_DEFAULTS,
    _duckdb_token_rollup,
    _token_cost_intelligence,
    _token_has_sqlite_table,
    _token_rollup,
    _token_rows_from_duckdb,
)
from .read_models_validation import _validation_outcome_intelligence, _validation_rollup

__all__ = [
    "COMPONENT_TABLES",
    "CORE_TABLES",
    "FACT_TABLES",
    "MODULE_SEGMENTS",
    "ScopeFilter",
    "_ATTENTION_EVENTS_VIEW_SQL",
    "_DECISION_EVENTS_VIEW_SQL",
    "_DUCKDB_COMPONENT_EVENT_TYPES",
    "_OUTCOME_EVENTS_VIEW_SQL",
    "_REPORTABLE_COST_VISIBILITIES",
    "_TOKEN_ROLLUP_DIM_DEFAULTS",
    "_add_condition",
    "_analytics_rows",
    "_attention_groups",
    "_attention_rollup",
    "_component_drilldowns",
    "_component_hardening_intelligence",
    "_component_usage",
    "_component_usage_from_events_fact",
    "_component_usage_rows",
    "_connect",
    "_distinct_count",
    "_drilldown_entry_points",
    "_duckdb_token_rollup",
    "_entity_counts",
    "_entity_drilldowns",
    "_first",
    "_json_list",
    "_json_object",
    "_none_if_unknown",
    "_outcome_rollup",
    "_outcome_row_count",
    "_process_run_drilldowns",
    "_process_runs_from_events",
    "_require_tables",
    "_research_decision_rollup",
    "_route_explainability",
    "_route_rollup",
    "_row_count",
    "_rows",
    "_scope_dict",
    "_scope_from_rollup_row",
    "_scoped_rows",
    "_scoped_rows_from_sql",
    "_scoped_summary",
    "_security_attribution",
    "_security_finding_row_count",
    "_security_remediation_intelligence",
    "_security_rollup",
    "_security_status_counts",
    "_source_tables_for_components",
    "_table_counts",
    "_token_cost_intelligence",
    "_token_has_sqlite_table",
    "_token_rollup",
    "_token_rows_from_duckdb",
    "_validation_outcome_intelligence",
    "_validation_rollup",
    "_where_scope",
    "_where_scope_project_only",
    "_with_authority",
    "component_usage_summary",
    "dashboard_attention_summary",
    "dashboard_module_read_models",
    "dashboard_module_segments",
    "global_telemetry_summary",
    "milestone_telemetry_summary",
    "process_run_timeline",
    "project_telemetry_summary",
    "task_telemetry_summary",
    "workflow_execution_graph",
]
