"""Expert workflow base definitions (the 10-workflow catalog data).

WO-GF-SHARED-INTEL-SPLIT: extracted from expert_workflows.py.
"""

from __future__ import annotations

from typing import Any

from .expert_workflows_constants import DESIGN_SPECIALIZED_SKILLS

_WORKFLOW_BASES: dict[str, dict[str, Any]] = {
    "api_integration_design_workflow": {
        "workflow_owner": "domains:fullstack/spec+integrate",
        "skill_owner": "ds-domains/fullstack",
        "purpose": "Design API and integration boundaries before client/server drift appears.",
        "when_to_run": [
            "new or changed routes",
            "client/server contract changes",
            "integration or auth boundary work",
        ],
        "when_not_to_run": ["pure copy changes", "offline docs with no API surface"],
        "input_contract": [
            "route shape",
            "auth/authz model",
            "schema/versioning needs",
            "client compatibility constraints",
        ],
        "output_contract": [
            "API contract",
            "risk findings",
            "validation plan",
            "client compatibility notes",
        ],
        "scores": ("api_contract_quality", "integration_resilience", "auth_boundary_confidence"),
        "evidence_requirements": [
            "route files",
            "schema/contracts",
            "auth middleware",
            "tests or API smoke evidence",
        ],
        "validation_requirements": ["contract tests", "authz checks", "error contract checks"],
        "dashboard_visibility": "Project Details API readiness and release blockers.",
        "contract_atlas_impact": "expert_workflow_system.api_integration_design",
        "privacy_boundary": "Do not expose private endpoint data or credentials in public docs.",
        "existing_owners": ["skills/domains/modes/fullstack", "core/production_readiness"],
        "overlap_status": {
            "decision": "strengthen_existing",
            "overlap_reason": "Fullstack spec mode already owns API contracts; readiness controls cover resilience.",
            "evidence": ["skills/domains/modes/fullstack/SKILL.md", "core/production_readiness"],
            "validation_requirement": "catalog test plus API readiness representative check",
            "rollback_supersession_plan": "Revert catalog mapping; fullstack skill remains unchanged.",
            "dashboard_project_health_impact": "API findings can affect readiness/release blockers.",
        },
    },
    "code_quality_architecture_workflow": {
        "workflow_owner": "quality:review+structure-audit",
        "skill_owner": "ds-quality",
        "purpose": "Evaluate maintainability, architecture boundaries, and correctness beyond lint and format.",
        "when_to_run": [
            "shared code changes",
            "architecture changes",
            "release readiness",
            "quality reviews",
        ],
        "when_not_to_run": ["single documentation typo", "non-code evidence-only update"],
        "input_contract": [
            "changed files",
            "module contracts",
            "test/lint evidence",
            "architecture constraints",
        ],
        "output_contract": [
            "quality scorecard",
            "findings",
            "remediation Work Orders",
            "missing evidence",
        ],
        "scores": (
            "readability",
            "duplication",
            "type_safety",
            "boundary_alignment",
            "testability",
        ),
        "evidence_requirements": [
            "diff",
            "tests",
            "module contracts",
            "imports/routes",
            "lint/type output",
        ],
        "validation_requirements": [
            "focused tests",
            "boundary checks where available",
            "review findings",
        ],
        "dashboard_visibility": "Project Details quality and release-readiness signals.",
        "contract_atlas_impact": "expert_workflow_system.code_quality_architecture",
        "privacy_boundary": "No private source snippets in public exports unless source is public.",
        "existing_owners": ["skills/core/modes/review", "skills/quality/modes/structure-audit"],
        "overlap_status": {
            "decision": "strengthen_existing",
            "overlap_reason": "Review and structure-audit already cover correctness and architecture shape.",
            "evidence": [
                "skills/core/modes/review/SKILL.md",
                "skills/quality/modes/structure-audit",
            ],
            "validation_requirement": "catalog scorecard test plus release-gate coverage",
            "rollback_supersession_plan": "Revert catalog mapping; review modes remain unchanged.",
            "dashboard_project_health_impact": "Quality blockers can lower health confidence and release readiness.",
        },
    },
    "data_modeling_authority_workflow": {
        "workflow_owner": "core:sqlite_authority",
        "skill_owner": "ds-quality/harden",
        "purpose": "Protect SQLite authority, read models, migrations, backfills, and projection boundaries.",
        "when_to_run": [
            "schema changes",
            "backfills",
            "read model changes",
            "authority/projection changes",
        ],
        "when_not_to_run": ["frontend-only copy updates", "non-authoritative markdown edits"],
        "input_contract": [
            "table ownership",
            "migration/backfill plan",
            "source refs",
            "rollback path",
        ],
        "output_contract": [
            "authority design review",
            "migration safety result",
            "manual-review flags",
        ],
        "scores": (
            "authority_fit",
            "migration_safety",
            "source_ref_coverage",
            "projection_boundary",
        ),
        "evidence_requirements": [
            "migrations",
            "schema pragma",
            "source refs",
            "read-model callers",
        ],
        "validation_requirements": [
            "migration tests",
            "idempotency checks",
            "live SQLite guard when applicable",
        ],
        "dashboard_visibility": "Project Details database/read-model readiness.",
        "contract_atlas_impact": "expert_workflow_system.data_modeling_authority",
        "privacy_boundary": "Do not print live DB contents or secrets; use schema and counts when possible.",
        "existing_owners": ["docs/DATABASE.md", "core/event_store", "core/analytics_ingestion.py"],
        "overlap_status": {
            "decision": "strengthen_existing",
            "overlap_reason": "SQLite and analytics ingestion already define authority tables and import paths.",
            "evidence": ["docs/DATABASE.md", "core/event_store/migrations"],
            "validation_requirement": "migration/idempotency tests and catalog validation",
            "rollback_supersession_plan": "Revert catalog mapping; schema authority remains migration-backed.",
            "dashboard_project_health_impact": "Unsafe migrations block readiness and release.",
        },
    },
    "documentation_quality_workflow": {
        "workflow_owner": "docs:quality",
        "skill_owner": "ds-core/explain",
        "purpose": "Evaluate whether docs are useful, current, installable, recoverable, and honest.",
        "when_to_run": ["docs changes", "product behavior changes", "release/publication checks"],
        "when_not_to_run": ["internal code-only change with docs reviewed no-change evidence"],
        "input_contract": ["changed docs", "product behavior", "commands", "known limitations"],
        "output_contract": ["docs usefulness scorecard", "drift findings", "examples to fix"],
        "scores": (
            "new_user_installability",
            "developer_contribution_clarity",
            "operator_recovery_clarity",
        ),
        "evidence_requirements": ["docs refs", "command validation", "README/PRD alignment"],
        "validation_requirements": ["docs drift gate", "command smoke where applicable"],
        "dashboard_visibility": "Contract Atlas docs freshness and Project Details docs gaps.",
        "contract_atlas_impact": "expert_workflow_system.documentation_quality",
        "privacy_boundary": "Public docs must not include private paths, telemetry, Work Orders, or career data.",
        "existing_owners": ["core/shared_intelligence/contract_registry.py", "docs/README.md"],
        "overlap_status": {
            "decision": "strengthen_existing",
            "overlap_reason": "Docs drift already tracks freshness; this adds usefulness criteria.",
            "evidence": ["interfaces/cli/contract_docs_drift_gate.py", "docs/README.md"],
            "validation_requirement": "contract docs drift gate plus catalog validation",
            "rollback_supersession_plan": "Revert catalog mapping; drift gate continues freshness checks.",
            "dashboard_project_health_impact": "Docs blockers affect publication readiness, not runtime health unless operator recovery is missing.",
        },
    },
    "frontend_design_excellence_workflow": {
        "workflow_owner": "quality:polish+domains:design",
        "skill_owner": "ds-quality/polish",
        "purpose": "Diagnose and improve UX, visual hierarchy, accessibility, responsive behavior, components, and design-to-code fit.",
        "when_to_run": [
            "UI changes",
            "dashboard changes",
            "public/portfolio pages",
            "design review",
        ],
        "when_not_to_run": ["backend-only work", "private CLI-only changes"],
        "input_contract": [
            "screens/routes",
            "design intent",
            "target users",
            "component/state evidence",
        ],
        "output_contract": [
            "design diagnosis",
            "scorecard",
            "frontend implementation contract",
            "validation checklist",
        ],
        "scores": (
            "ux_clarity",
            "visual_hierarchy",
            "accessibility",
            "responsive_behavior",
            "component_consistency",
            "data_visualization",
            "implementation_feasibility",
        ),
        "evidence_requirements": [
            "screenshots",
            "DOM/routes",
            "CSS/components",
            "a11y/responsive checks",
        ],
        "validation_requirements": [
            "browser screenshot or Playwright when approved",
            "accessibility checklist",
        ],
        "dashboard_visibility": "Project Details design/readiness and dashboard attention for visual blockers.",
        "contract_atlas_impact": "expert_workflow_system.frontend_design_excellence",
        "privacy_boundary": "Screenshots may expose private data; sanitize before publication.",
        "existing_owners": ["skills/quality/modes/polish", "skills/domains/modes/design"],
        "specialized_skills": list(DESIGN_SPECIALIZED_SKILLS),
        "overlap_status": {
            "decision": "split_existing",
            "overlap_reason": "Polish remains the execution skill; specialized review lenses make results reusable without new monolith.",
            "evidence": [
                "skills/quality/modes/polish/SKILL.md",
                "skills/domains/modes/design/SKILL.md",
            ],
            "validation_requirement": "specialized design skill coverage and score rubric tests",
            "rollback_supersession_plan": "Remove catalog specializations; polish/design skills remain active.",
            "dashboard_project_health_impact": "Accessibility and responsive blockers affect readiness.",
        },
    },
    "intentional_implementation_workflow": {
        "workflow_owner": "core:build",
        "skill_owner": "ds-core",
        "purpose": "Require a lightweight implementation contract before code changes.",
        "when_to_run": ["code changes", "schema changes", "workflow changes", "runtime changes"],
        "when_not_to_run": ["read-only inspection", "status reporting", "pure validation"],
        "input_contract": [
            "why code is needed",
            "problem solved",
            "affected layer/module/contract",
            "alternatives considered",
            "best-practice basis",
            "expected impact",
            "validation plan",
            "rollback plan",
        ],
        "output_contract": [
            "implementation contract",
            "changed-file scope",
            "validation evidence",
            "post-change review",
        ],
        "scores": ("implementation_intent_clarity", "scope_fit", "rollback_confidence"),
        "evidence_requirements": [
            "problem statement",
            "affected contracts",
            "test plan",
            "rollback note",
        ],
        "validation_requirements": [
            "post-change correctness review",
            "focused tests",
            "docs drift if impacted",
        ],
        "dashboard_visibility": "Work Order details and release readiness evidence.",
        "contract_atlas_impact": "expert_workflow_system.intentional_implementation",
        "privacy_boundary": "Implementation evidence may remain private when it references local state.",
        "existing_owners": ["skills/core/modes/build", "core/work_orders"],
        "overlap_status": {
            "decision": "strengthen_existing",
            "overlap_reason": "Build and Work Orders already own implementation scope; this formalizes the pre-change contract.",
            "evidence": ["skills/core/modes/build/SKILL.md", "core/work_orders"],
            "validation_requirement": "catalog test asserts required implementation contract fields",
            "rollback_supersession_plan": "Revert catalog mapping; existing build mode continues.",
            "dashboard_project_health_impact": "Missing implementation contract becomes release-readiness attention.",
        },
    },
    "performance_efficiency_workflow": {
        "workflow_owner": "quality:debug/performance",
        "skill_owner": "ds-quality",
        "purpose": "Improve runtime, query, frontend, API, validation, and adapter/tool efficiency.",
        "when_to_run": [
            "slow paths",
            "large payloads",
            "token inefficiency",
            "repeated retries",
            "release hardening",
        ],
        "when_not_to_run": ["unmeasured aesthetic preference", "no performance-sensitive surface"],
        "input_contract": [
            "symptom/metric",
            "trace or profile evidence",
            "affected surface",
            "success target",
        ],
        "output_contract": ["bottleneck diagnosis", "efficiency scorecard", "minimal fix plan"],
        "scores": (
            "latency_confidence",
            "query_efficiency",
            "frontend_render_cost",
            "adapter_efficiency",
        ),
        "evidence_requirements": [
            "profile/logs",
            "query plans if relevant",
            "payload sizes",
            "adapter usage records",
        ],
        "validation_requirements": ["before/after measurement or unavailable reason"],
        "dashboard_visibility": "Project Details performance/readiness and AI operational value telemetry.",
        "contract_atlas_impact": "expert_workflow_system.performance_efficiency",
        "privacy_boundary": "Do not publish private traces or provider billing credentials.",
        "existing_owners": [
            "skills/quality/modes/debug/references/performance-issues.md",
            "core/shared_intelligence/usage_accounting.py",
        ],
        "overlap_status": {
            "decision": "strengthen_existing",
            "overlap_reason": "Debug references cover performance diagnosis; usage accounting covers adapter efficiency.",
            "evidence": [
                "skills/quality/modes/debug/references/performance-issues.md",
                "core/shared_intelligence/usage_accounting.py",
            ],
            "validation_requirement": "performance score rubric and usage-accounting policy tests",
            "rollback_supersession_plan": "Revert catalog mapping; debug performance references remain.",
            "dashboard_project_health_impact": "Measured performance blockers can affect readiness.",
        },
    },
    "product_demo_and_case_study_workflow": {
        "workflow_owner": "docs:portfolio_case_study",
        "skill_owner": "ds-core/explain",
        "purpose": "Turn real project evidence into sanitized demos, scripts, and case-study material.",
        "when_to_run": ["portfolio/demo planning", "publication readiness", "case-study drafting"],
        "when_not_to_run": [
            "no evidence refs",
            "private project details without sanitization approval",
        ],
        "input_contract": [
            "project evidence refs",
            "audience",
            "before/after proof",
            "privacy boundary",
        ],
        "output_contract": [
            "positioning",
            "demo script",
            "case-study outline",
            "sanitization checklist",
        ],
        "scores": ("proof_strength", "demo_readiness", "public_sanitization_readiness"),
        "evidence_requirements": [
            "validation refs",
            "screenshots needed",
            "metrics evidence or missing flags",
        ],
        "validation_requirements": [
            "sanitized export review",
            "operator approval before public use",
        ],
        "dashboard_visibility": "Portfolio/case-study readiness and publication boundary attention.",
        "contract_atlas_impact": "expert_workflow_system.product_demo_case_study",
        "privacy_boundary": "Public case studies require explicit sanitization and approval.",
        "existing_owners": ["docs/demo-script.md", "docs/portfolio-case-study.md"],
        "overlap_status": {
            "decision": "strengthen_existing",
            "overlap_reason": "Demo and portfolio docs already exist; this makes them evidence-backed workflows.",
            "evidence": ["docs/demo-script.md", "docs/portfolio-case-study.md"],
            "validation_requirement": "catalog test plus publication boundary check",
            "rollback_supersession_plan": "Revert catalog mapping; docs remain reference material.",
            "dashboard_project_health_impact": "Does not affect project health unless used for publication readiness.",
        },
    },
    "root_cause_debugging_workflow": {
        "workflow_owner": "quality:debug",
        "skill_owner": "ds-quality",
        "purpose": "Prevent random trial-and-error debugging through hypothesis-ranked root cause analysis.",
        "when_to_run": ["bug reports", "failing validation", "unexpected runtime behavior"],
        "when_not_to_run": ["known simple typo with direct fix and validation", "feature planning"],
        "input_contract": ["symptom", "reproduction plan", "logs/traces", "hypotheses"],
        "output_contract": [
            "root cause",
            "minimal fix",
            "regression test",
            "verification evidence",
        ],
        "scores": ("reproduction_quality", "root_cause_confidence", "regression_protection"),
        "evidence_requirements": [
            "error output",
            "repro steps",
            "hypothesis log",
            "fix verification",
        ],
        "validation_requirements": ["regression test when feasible", "post-fix verification"],
        "dashboard_visibility": "Debug findings, validation failures, and remediation Work Orders.",
        "contract_atlas_impact": "expert_workflow_system.root_cause_debugging",
        "privacy_boundary": "Logs may contain private data; redact before public export.",
        "existing_owners": ["skills/quality/modes/debug/SKILL.md"],
        "overlap_status": {
            "decision": "keep_existing",
            "overlap_reason": "Debug skill already implements disciplined hypothesis testing.",
            "evidence": ["skills/quality/modes/debug/SKILL.md"],
            "validation_requirement": "catalog maps existing debug behavior without duplicate skill",
            "rollback_supersession_plan": "No supersession; keep debug mode as canonical owner.",
            "dashboard_project_health_impact": "Unresolved root cause affects health and release readiness.",
        },
    },
    "seo_content_growth_workflow": {
        "workflow_owner": "domains:website/content",
        "skill_owner": "ds-domains/website",
        "purpose": "Support public-facing sites, docs, portfolio pages, product pages, and marketing surfaces.",
        "when_to_run": ["public/content/marketing surfaces", "portfolio pages", "product pages"],
        "when_not_to_run": ["backend-only work", "private dashboards", "no public content surface"],
        "input_contract": [
            "page intent",
            "audience",
            "metadata/schema",
            "content structure",
            "performance evidence",
        ],
        "output_contract": [
            "SEO/content findings",
            "snippet recommendations",
            "content gap analysis",
        ],
        "scores": (
            "technical_seo",
            "content_intent_fit",
            "conversion_copy_quality",
            "brand_alignment",
        ),
        "evidence_requirements": [
            "routes/pages",
            "metadata",
            "structured data",
            "content copy",
            "performance signals",
        ],
        "validation_requirements": [
            "only run when public/content surface is present",
            "source refs for market claims",
        ],
        "dashboard_visibility": "Publication/readiness and content-surface attention.",
        "contract_atlas_impact": "expert_workflow_system.seo_content_growth",
        "privacy_boundary": "Do not publish private project details, career data, or unsupported claims.",
        "existing_owners": ["skills/domains/modes/website", "docs/PUBLICATION_BOUNDARY.md"],
        "overlap_status": {
            "decision": "strengthen_existing",
            "overlap_reason": "Website domain owns public surfaces; publication boundary owns privacy limits.",
            "evidence": ["skills/domains/modes/website", "docs/PUBLICATION_BOUNDARY.md"],
            "validation_requirement": "catalog validates when-not-to-run backend-only boundary",
            "rollback_supersession_plan": "Revert catalog mapping; website skill remains.",
            "dashboard_project_health_impact": "SEO affects public readiness, not backend health.",
        },
    },
}
