"""Unit tests for think mode research integration (Phase 7, T144).

Tests verify that spec.md files generated by think mode with --research flag
include proper research findings sections with source quality tiers and
confidence scoring.

Tests cover:
1. Research flag presence adds "Research Findings" section to spec.md
2. Tier 1 sources appear before Tier 2/3 sources in findings
3. Low confidence research (<0.6) shows "unverified" warning label
"""

from __future__ import annotations

import re
import tempfile
from pathlib import Path
from typing import List
from unittest.mock import patch, MagicMock

import pytest

from control.research import web as web_research

# ── Test Fixtures ──────────────────────────────────────────────────────────


@pytest.fixture
def mock_high_confidence_report() -> web_research.ResearchReport:
    """Create a high-confidence research report with multiple tier 1 sources."""
    sources = [
        web_research.Source(
            url="https://github.com/python/cpython",
            title="Python Official Repository",
            snippet="Official Python source code and documentation",
            tier=1,
        ),
        web_research.Source(
            url="https://docs.python.org/3/library/asyncio.html",
            title="asyncio - Python Documentation",
            snippet="Official asyncio documentation",
            tier=1,
        ),
        web_research.Source(
            url="https://realpython.com/async-io-python/",
            title="Async IO in Python - Real Python",
            snippet="Comprehensive tutorial on async IO",
            tier=2,
        ),
    ]

    return web_research.ResearchReport(
        topic="Python async programming",
        sources=sources,
        findings=web_research.summarize_findings(sources),
        confidence=0.87,  # High confidence (>0.6)
        triangulation=1.0,
    )


@pytest.fixture
def mock_low_confidence_report() -> web_research.ResearchReport:
    """Create a low-confidence research report with only tier 3 sources."""
    sources = [
        web_research.Source(
            url="https://stackoverflow.com/questions/12345/async-python",
            title="How to use async in Python? - Stack Overflow",
            snippet="Community discussion on async Python",
            tier=3,
        ),
        web_research.Source(
            url="https://reddit.com/r/Python/comments/abc123/",
            title="Async Python Discussion - Reddit",
            snippet="Reddit thread on async Python patterns",
            tier=3,
        ),
    ]

    return web_research.ResearchReport(
        topic="Python async patterns",
        sources=sources,
        findings=web_research.summarize_findings(sources),
        confidence=0.45,  # Low confidence (<0.6)
        triangulation=0.67,
    )


@pytest.fixture
def mock_mixed_tier_report() -> web_research.ResearchReport:
    """Create research report with mixed tier sources for ordering tests."""
    sources = [
        # Tier 2 source (should appear second)
        web_research.Source(
            url="https://realpython.com/async-io-python/",
            title="Async IO Tutorial - Real Python",
            snippet="Tutorial on async IO",
            tier=2,
        ),
        # Tier 1 source (should appear first)
        web_research.Source(
            url="https://github.com/python/cpython",
            title="Python GitHub Repository",
            snippet="Official Python repository",
            tier=1,
        ),
        # Tier 3 source (should appear last)
        web_research.Source(
            url="https://stackoverflow.com/questions/999/async",
            title="Stack Overflow Question",
            snippet="Community Q&A",
            tier=3,
        ),
        # Another tier 1 source (should appear with first tier 1)
        web_research.Source(
            url="https://docs.python.org/3/",
            title="Python Documentation",
            snippet="Official docs",
            tier=1,
        ),
    ]

    return web_research.ResearchReport(
        topic="Python async best practices",
        sources=sources,
        findings=web_research.summarize_findings(sources),
        confidence=0.72,
        triangulation=1.0,
    )


def generate_spec_md_with_research(report: web_research.ResearchReport) -> str:
    """Generate a minimal spec.md with research findings section.

    This simulates what the think mode would output when --research flag is used.

    Args:
        report: ResearchReport to include in spec

    Returns:
        Markdown content for spec.md file
    """
    confidence_label = (
        "High" if report.confidence > 0.75 else "Medium" if report.confidence >= 0.5 else "Low"
    )

    # Add unverified warning for low confidence
    warning = ""
    if report.confidence < 0.6:
        warning = " ⚠️ **UNVERIFIED** - Low confidence, proceed with caution"

    # Note: report.findings already includes "## Research Findings" header and tier sections
    # We just need to add the metadata (topic, confidence, triangulation) before the tier sections

    # Extract tier sections from findings (skip the header)
    findings_content = report.findings
    if findings_content.startswith("## Research Findings"):
        # Remove the header and extract just the tier sections
        findings_content = findings_content.replace("## Research Findings\n", "", 1)

    spec_content = f"""# Feature Specification

## Overview
This is a test specification document.

## User Stories
- **P1:** User can perform basic task
- **P2:** User can configure advanced options

## Functional Requirements
- **FR-001:** System MUST implement core functionality
- **FR-002:** System MUST validate user input

## Decision Rationale
We chose approach A because of performance benefits.

## Research Findings

**Topic:** {report.topic}
**Confidence:** {report.confidence:.2f} ({confidence_label}){warning}
**Triangulation:** {report.triangulation:.2f} ({len(report.sources)} sources)
{findings_content}

## Success Criteria
- **SC-001:** Feature completes in <500ms
- **SC-002:** 95% user task completion rate
"""

    return spec_content


# ── Tests ──────────────────────────────────────────────────────────────────


def test_research_flag(mock_high_confidence_report: web_research.ResearchReport):
    """Verify spec.md contains 'Research Findings' section when --research flag is used.

    When think mode is invoked with --research flag, the generated spec.md MUST
    include a "## Research Findings" section with topic, confidence, triangulation,
    and source list.

    Test strategy:
    1. Mock research API to return high-confidence report
    2. Generate spec.md content with research section
    3. Verify "Research Findings" header exists
    4. Verify topic, confidence, and triangulation are present
    """
    # Generate spec.md content with research
    spec_content = generate_spec_md_with_research(mock_high_confidence_report)

    # Verify Research Findings section exists
    assert "## Research Findings" in spec_content, "spec.md missing '## Research Findings' section"

    # Verify topic is included
    assert "**Topic:**" in spec_content, "Research findings missing topic field"
    assert (
        mock_high_confidence_report.topic in spec_content
    ), f"Topic '{mock_high_confidence_report.topic}' not found in spec"

    # Verify confidence score is included
    assert "**Confidence:**" in spec_content, "Research findings missing confidence field"
    assert "0.87" in spec_content, "Confidence score not displayed in spec"

    # Verify triangulation score is included
    assert "**Triangulation:**" in spec_content, "Research findings missing triangulation field"
    assert (
        "1.0" in spec_content or "1.00" in spec_content
    ), "Triangulation score not displayed in spec"

    # Verify source count is mentioned
    assert "3 sources" in spec_content.lower(), "Source count not mentioned in research section"


def test_source_tiers(mock_mixed_tier_report: web_research.ResearchReport):
    """Verify Tier 1 sources appear before Tier 2/3 sources in research findings.

    Research findings MUST be organized by tier with Tier 1 (official docs, GitHub)
    appearing first, followed by Tier 2 (blogs), then Tier 3 (forums).

    Test strategy:
    1. Create report with mixed tier sources (tier 2, tier 1, tier 3, tier 1)
    2. Generate spec.md content
    3. Verify tier sections appear in order: Tier 1 → Tier 2 → Tier 3
    4. Verify tier 1 sources appear in Tier 1 section only
    """
    # Generate spec.md content with mixed tier sources
    spec_content = generate_spec_md_with_research(mock_mixed_tier_report)

    # Extract research findings section (up to next ## heading)
    findings_match = re.search(
        r"## Research Findings.*?(?=^##\s|\Z)", spec_content, re.DOTALL | re.MULTILINE
    )
    assert findings_match, "Could not extract Research Findings section"
    findings_section = findings_match.group(0)

    # Find tier section positions (account for possible whitespace)
    tier1_match = re.search(r"###\s+Primary Sources \(Tier 1\)", findings_section)
    tier2_match = re.search(r"###\s+Technical Content \(Tier 2\)", findings_section)
    tier3_match = re.search(r"###\s+Community Discussion \(Tier 3\)", findings_section)

    # Verify tier sections exist
    assert tier1_match, f"Tier 1 section header not found in:\n{findings_section[:500]}"
    assert tier2_match, f"Tier 2 section header not found in:\n{findings_section[:500]}"
    assert tier3_match, f"Tier 3 section header not found in:\n{findings_section[:500]}"

    # Verify tier sections appear in correct order
    tier1_pos = tier1_match.start()
    tier2_pos = tier2_match.start()
    tier3_pos = tier3_match.start()

    assert tier1_pos < tier2_pos, "Tier 1 section must appear before Tier 2"
    assert tier2_pos < tier3_pos, "Tier 2 section must appear before Tier 3"

    # Verify tier 1 sources appear in tier 1 section only
    tier1_section = findings_section[tier1_pos:tier2_pos]
    assert "Python GitHub Repository" in tier1_section, "Tier 1 source missing from Tier 1 section"
    assert "Python Documentation" in tier1_section, "Tier 1 source missing from Tier 1 section"

    # Verify tier 2 sources appear in tier 2 section only
    tier2_section = findings_section[tier2_pos:tier3_pos]
    assert "Real Python" in tier2_section, "Tier 2 source missing from Tier 2 section"

    # Verify tier 3 sources appear in tier 3 section only
    tier3_section = findings_section[tier3_pos:]
    assert "Stack Overflow" in tier3_section, "Tier 3 source missing from Tier 3 section"


def test_low_confidence_warning(mock_low_confidence_report: web_research.ResearchReport):
    """Verify low confidence research (<0.6) shows 'UNVERIFIED' warning label.

    When research confidence score is below 0.6 (indicating poor source quality
    or insufficient triangulation), the spec MUST include an 'UNVERIFIED' warning
    to alert users that findings may be unreliable.

    Test strategy:
    1. Mock research API to return low-confidence report (confidence=0.45)
    2. Generate spec.md content
    3. Verify 'UNVERIFIED' warning appears near confidence score
    4. Verify warning includes cautionary language
    """
    # Generate spec.md content with low confidence report
    spec_content = generate_spec_md_with_research(mock_low_confidence_report)

    # Verify UNVERIFIED warning is present
    assert (
        "UNVERIFIED" in spec_content
    ), "Missing 'UNVERIFIED' warning for low confidence (<0.6) research"

    # Verify warning appears near confidence score
    confidence_match = re.search(
        r"\*\*Confidence:\*\*.*?(UNVERIFIED|⚠️).*?Low", spec_content, re.DOTALL | re.IGNORECASE
    )
    assert confidence_match, "UNVERIFIED warning not positioned near confidence score"

    # Verify confidence is labeled as "Low"
    assert "Low" in spec_content, "Low confidence not labeled as 'Low'"

    # Verify cautionary language is present
    caution_patterns = [
        r"proceed with caution",
        r"low confidence",
        r"unreliable",
        r"verify independently",
    ]

    has_caution = any(
        re.search(pattern, spec_content, re.IGNORECASE) for pattern in caution_patterns
    )
    assert has_caution, "Missing cautionary language for low confidence research"

    # Verify confidence score is displayed correctly
    assert "0.45" in spec_content, "Confidence score 0.45 not displayed in spec"


def test_research_api_integration():
    """Verify think mode calls research API with correct parameters.

    This test mocks the research API endpoint to verify that think mode
    constructs the correct API request when --research flag is used.

    Test strategy:
    1. Mock POST /api/discovery/research endpoint
    2. Simulate think mode calling research API
    3. Verify request includes topic and focus_areas
    4. Verify response is parsed correctly
    """
    # Mock API response
    mock_api_response = {
        "topic": "FastAPI async performance",
        "sources": [
            {
                "url": "https://github.com/tiangolo/fastapi",
                "title": "FastAPI GitHub",
                "snippet": "Modern async web framework",
                "tier": 1,
            }
        ],
        "findings": "## Research Findings\n\n### Primary Sources (Tier 1)\n- **[FastAPI GitHub](https://github.com/tiangolo/fastapi)**\n  Modern async web framework\n",
        "confidence": 0.88,
        "triangulation": 0.33,
        "cache_id": "abc123",
    }

    with patch("control.research.web.research_topic") as mock_research:
        # Configure mock to return ResearchReport
        mock_report = web_research.ResearchReport(
            topic=mock_api_response["topic"],
            sources=[web_research.Source(**s) for s in mock_api_response["sources"]],
            findings=mock_api_response["findings"],
            confidence=mock_api_response["confidence"],
            triangulation=mock_api_response["triangulation"],
        )
        mock_research.return_value = mock_report

        # Simulate think mode calling research_topic
        topic = "FastAPI async performance"
        focus_areas = ["benchmarks", "best practices"]

        result = web_research.research_topic(topic, focus_areas)

        # Verify research_topic was called with correct params
        mock_research.assert_called_once_with(topic, focus_areas)

        # Verify result has expected structure
        assert result.topic == topic
        assert len(result.sources) == 1
        assert result.confidence == 0.88
        assert result.triangulation == 0.33


def test_research_findings_markdown_format(
    mock_high_confidence_report: web_research.ResearchReport,
):
    """Verify research findings use correct markdown format in spec.md.

    Research findings section MUST use proper markdown formatting:
    - H2 header for section title
    - Bold for field labels
    - Markdown links for sources
    - Proper list formatting

    Test strategy:
    1. Generate spec.md with research findings
    2. Verify markdown structure with regex patterns
    3. Check headers, bold text, links, and lists
    """
    spec_content = generate_spec_md_with_research(mock_high_confidence_report)

    # Verify H2 header for section
    assert re.search(
        r"^## Research Findings$", spec_content, re.MULTILINE
    ), "Research Findings section must use H2 header (##)"

    # Verify bold field labels
    bold_labels = ["**Topic:**", "**Confidence:**", "**Triangulation:**"]
    for label in bold_labels:
        assert label in spec_content, f"Missing bold label: {label}"

    # Verify markdown links in sources
    link_pattern = r"\[.*?\]\(https?://.*?\)"
    links = re.findall(link_pattern, spec_content)
    assert len(links) >= 3, f"Expected at least 3 markdown links for sources, found {len(links)}"

    # Verify tier section headers use H3
    tier_header_pattern = (
        r"^### (Primary Sources|Technical Content|Community Discussion) \(Tier \d\)$"
    )
    tier_headers = re.findall(tier_header_pattern, spec_content, re.MULTILINE)
    assert len(tier_headers) >= 1, "Missing tier section headers (H3)"

    # Verify bullet list formatting for sources
    bullet_pattern = r"^- \*\*\[.*?\]\(.*?\)\*\*$"
    bullets = re.findall(bullet_pattern, spec_content, re.MULTILINE)
    assert len(bullets) >= 3, f"Expected at least 3 bulleted source entries, found {len(bullets)}"


def test_no_research_flag_no_section():
    """Verify spec.md does NOT include Research Findings when --research flag is omitted.

    When think mode is invoked WITHOUT --research flag, the spec.md MUST NOT
    include the Research Findings section.

    Test strategy:
    1. Generate spec.md without research (simulate no --research flag)
    2. Verify "Research Findings" section is absent
    """
    spec_without_research = """# Feature Specification

## Overview
This is a test specification document.

## User Stories
- **P1:** User can perform basic task
- **P2:** User can configure advanced options

## Functional Requirements
- **FR-001:** System MUST implement core functionality

## Decision Rationale
We chose approach A because of performance benefits.

## Success Criteria
- **SC-001:** Feature completes in <500ms
"""

    # Verify Research Findings section is NOT present
    assert (
        "## Research Findings" not in spec_without_research
    ), "spec.md should NOT include Research Findings without --research flag"

    assert (
        "**Topic:**" not in spec_without_research
    ), "spec.md should NOT include research topic without --research flag"

    assert (
        "**Confidence:**" not in spec_without_research
    ), "spec.md should NOT include confidence score without --research flag"
