"""Deterministic Handoff Packet generation — facade over the split modules.

WO-SPLIT-HANDOFF: implementation moved to handoff_{constants,helpers,
decision,build,validate,security}.py; this module re-exports the public API
so existing `from core.work_orders.handoff import X` callers are unchanged.
"""

from __future__ import annotations

from .handoff_constants import (
    BLOCKING_FAILED_EVALS,
    CONSTRAINT_TERMS,
    DECISION_TAXONOMIES,
    FAIL,
    FRESH_SESSION_RULE,
    HANDOFF_CONSTRAINT_PRESERVATION,
    HANDOFF_CURRENT_STATE_COMPLETENESS,
    HANDOFF_EVAL_TYPES,
    HANDOFF_EXECUTION_READINESS,
    HANDOFF_FRESH_SESSION_SUFFICIENCY,
    HANDOFF_HOOK_BEHAVIOR_AWARENESS,
    HANDOFF_INDEX_STATE_REQUIREMENTS,
    HANDOFF_OPERATOR_DECISION_GATE,
    HANDOFF_PATH_INTEGRITY,
    HANDOFF_PROMPT_COMPLETENESS,
    HANDOFF_PUSH_EVIDENCE_REQUIREMENTS,
    HANDOFF_PUSH_EXECUTION_COMPLETENESS,
    HANDOFF_PUSH_TARGET_CONSTRAINTS,
    HANDOFF_RECOVERY_MODE_COMPLETENESS,
    HANDOFF_RECOVERY_OPTION_CLARITY,
    HANDOFF_SELF_VALIDATION,
    HANDOFF_TYPES,
    HANDOFF_TYPE_APPROVED_MUTATION_EXECUTION,
    HANDOFF_TYPE_COMMIT_EXECUTION,
    HANDOFF_TYPE_HOLD_REVIEW,
    HANDOFF_TYPE_NORMAL_NEXT_WORK_ORDER,
    HANDOFF_TYPE_RECOVERY_DECISION,
    HANDOFF_TYPE_RECOVERY_EXECUTION,
    HOLD,
    PHASE_TYPE_APPROVED_MUTATION,
    PHASE_TYPE_COMMIT_PLANNING,
    PHASE_TYPE_NORMAL_NEXT_WORK_ORDER,
    PHASE_TYPE_PRODUCT_CLOSEOUT,
    PHASE_TYPE_PUSH_PLANNING,
    PHASE_TYPE_RECOVERY_DECISION,
    PUSH_EXECUTION_REQUIRED_SECTIONS,
    READY,
    READY_TO_COPY_NEXT_PROMPT_CONTRACT_COMPLIANCE,
    READY_WITH_CONSTRAINTS,
    RECOVERY_DECISION_REQUIRED_SECTIONS,
    REQUIRED_HANDOFF_SECTIONS,
    SECURITY_HANDOFF_EVAL_TYPES,
    SECURITY_HANDOFF_FINDING_REFS_PRESENT,
    SECURITY_HANDOFF_FORBIDDEN_ACTIONS_PRESERVED,
    SECURITY_HANDOFF_NO_COMMIT_WITHOUT_COMMIT_PHASE,
    SECURITY_HANDOFF_NO_TARGET_MUTATION_WITHOUT_APPROVAL,
    SECURITY_HANDOFF_RELEASE_GATE_PRESERVED,
    SECURITY_HANDOFF_REMEDIATION_SCOPE_BOUNDED,
    SECURITY_HANDOFF_TARGET_CONSTRAINTS_PRESERVED,
    SECURITY_REMEDIATION_REQUIRED_SECTIONS,
    UNDERSTANDING_REQUIRED_TERMS,
)
from .handoff_decision import (
    determine_next_action_decision,
    determine_sequential_readiness,
)
from .handoff_build import (
    build_handoff_prompt,
    build_handoff_sections,
)
from .handoff_validate import (
    dry_run_handoff_prompt,
    evaluate_handoff_prompt,
    parse_prompt_sections,
    regenerate_handoff_prompt,
    self_validate_generated_handoff,
)
from .handoff_security import (
    build_security_post_remediation_review_handoff_prompt,
    build_security_remediation_mutation_handoff_prompt,
    build_security_review_remediation_handoff_prompt,
    evaluate_security_post_remediation_review_handoff_prompt,
    evaluate_security_remediation_mutation_handoff_prompt,
    evaluate_security_review_next_handoff_prompt,
)

__all__ = [
    "BLOCKING_FAILED_EVALS",
    "CONSTRAINT_TERMS",
    "DECISION_TAXONOMIES",
    "FAIL",
    "FRESH_SESSION_RULE",
    "HANDOFF_CONSTRAINT_PRESERVATION",
    "HANDOFF_CURRENT_STATE_COMPLETENESS",
    "HANDOFF_EVAL_TYPES",
    "HANDOFF_EXECUTION_READINESS",
    "HANDOFF_FRESH_SESSION_SUFFICIENCY",
    "HANDOFF_HOOK_BEHAVIOR_AWARENESS",
    "HANDOFF_INDEX_STATE_REQUIREMENTS",
    "HANDOFF_OPERATOR_DECISION_GATE",
    "HANDOFF_PATH_INTEGRITY",
    "HANDOFF_PROMPT_COMPLETENESS",
    "HANDOFF_PUSH_EVIDENCE_REQUIREMENTS",
    "HANDOFF_PUSH_EXECUTION_COMPLETENESS",
    "HANDOFF_PUSH_TARGET_CONSTRAINTS",
    "HANDOFF_RECOVERY_MODE_COMPLETENESS",
    "HANDOFF_RECOVERY_OPTION_CLARITY",
    "HANDOFF_SELF_VALIDATION",
    "HANDOFF_TYPES",
    "HANDOFF_TYPE_APPROVED_MUTATION_EXECUTION",
    "HANDOFF_TYPE_COMMIT_EXECUTION",
    "HANDOFF_TYPE_HOLD_REVIEW",
    "HANDOFF_TYPE_NORMAL_NEXT_WORK_ORDER",
    "HANDOFF_TYPE_RECOVERY_DECISION",
    "HANDOFF_TYPE_RECOVERY_EXECUTION",
    "HOLD",
    "PHASE_TYPE_APPROVED_MUTATION",
    "PHASE_TYPE_COMMIT_PLANNING",
    "PHASE_TYPE_NORMAL_NEXT_WORK_ORDER",
    "PHASE_TYPE_PRODUCT_CLOSEOUT",
    "PHASE_TYPE_PUSH_PLANNING",
    "PHASE_TYPE_RECOVERY_DECISION",
    "PUSH_EXECUTION_REQUIRED_SECTIONS",
    "READY",
    "READY_TO_COPY_NEXT_PROMPT_CONTRACT_COMPLIANCE",
    "READY_WITH_CONSTRAINTS",
    "RECOVERY_DECISION_REQUIRED_SECTIONS",
    "REQUIRED_HANDOFF_SECTIONS",
    "SECURITY_HANDOFF_EVAL_TYPES",
    "SECURITY_HANDOFF_FINDING_REFS_PRESENT",
    "SECURITY_HANDOFF_FORBIDDEN_ACTIONS_PRESERVED",
    "SECURITY_HANDOFF_NO_COMMIT_WITHOUT_COMMIT_PHASE",
    "SECURITY_HANDOFF_NO_TARGET_MUTATION_WITHOUT_APPROVAL",
    "SECURITY_HANDOFF_RELEASE_GATE_PRESERVED",
    "SECURITY_HANDOFF_REMEDIATION_SCOPE_BOUNDED",
    "SECURITY_HANDOFF_TARGET_CONSTRAINTS_PRESERVED",
    "SECURITY_REMEDIATION_REQUIRED_SECTIONS",
    "UNDERSTANDING_REQUIRED_TERMS",
    "build_handoff_prompt",
    "build_handoff_sections",
    "build_security_post_remediation_review_handoff_prompt",
    "build_security_remediation_mutation_handoff_prompt",
    "build_security_review_remediation_handoff_prompt",
    "determine_next_action_decision",
    "determine_sequential_readiness",
    "dry_run_handoff_prompt",
    "evaluate_handoff_prompt",
    "evaluate_security_post_remediation_review_handoff_prompt",
    "evaluate_security_remediation_mutation_handoff_prompt",
    "evaluate_security_review_next_handoff_prompt",
    "parse_prompt_sections",
    "regenerate_handoff_prompt",
    "self_validate_generated_handoff",
]
