"""PRD-driven milestone planning and next-action classification — facade.

WO-GF-WO-LIFECYCLE: implementation moved to milestones_{shared,completion,
classify}.py; this module re-exports the public API so existing
``from core.work_orders.milestones import X`` callers — including
``core/work_orders/__init__.py``'s eager import of ``classify_next_action``,
``handoff_required_for_decision``, ``validate_authority_pack``, and
``validate_milestone_completion_criteria`` — are unchanged.
"""

from __future__ import annotations

from .milestones_classify import (
    _first_pending_step,
    _handoff_reason_for_step_type,
    _is_external_project_work,
    _is_low_risk_auto_continue,
    _milestone_complete,
    _milestone_completion_requires_handoff,
    _requires_operator_approval,
    _stage_gate_block,
    _step_id,
    _step_type,
    classify_next_action,
    handoff_required_for_decision,
)
from .milestones_completion import validate_authority_pack, validate_milestone_completion_criteria
from .milestones_shared import (
    ALLOWED_HANDOFF_REASONS,
    DEFAULT_PAUSED_EXTERNAL_PROJECTS,
    HANDOFF_REASON_ARTIFACT_LIFECYCLE_REQUIRED,
    HANDOFF_REASON_BY_STEP_TYPE,
    HANDOFF_REASON_COMMIT_REQUIRED,
    HANDOFF_REASON_CONTEXT_TRANSFER,
    HANDOFF_REASON_DATABASE_MUTATION_REQUIRED,
    HANDOFF_REASON_DDL_DML_REQUIRED,
    HANDOFF_REASON_EXTERNAL_RESUME_REQUIRED,
    HANDOFF_REASON_FAILED_VALIDATION,
    HANDOFF_REASON_HARD_BLOCKER,
    HANDOFF_REASON_MATERIAL_RISK_BOUNDARY,
    HANDOFF_REASON_MIGRATION_REQUIRED,
    HANDOFF_REASON_MILESTONE_COMPLETION,
    HANDOFF_REASON_NONE,
    HANDOFF_REASON_OPERATOR_APPROVAL,
    HANDOFF_REASON_OPERATOR_DECISION,
    HANDOFF_REASON_PACKAGE_REQUIRED,
    HANDOFF_REASON_PAUSE_RESUME,
    HANDOFF_REASON_PUSH_DEPLOY_REQUIRED,
    HANDOFF_REASON_ROLLBACK_UNCERTAINTY,
    HANDOFF_REASON_RUNTIME_VALIDATION_REQUIRED,
    HANDOFF_REASON_SECRET_REQUIRED,
    HANDOFF_REASON_SESSION_TRANSFER,
    HANDOFF_REASON_USER_EXPORT,
    INVALID_HANDOFF_REASONS,
    LOW_RISK_STEP_TYPES,
    MATERIAL_RISK_STEP_TYPES,
    NEXT_ACTIONS,
    NEXT_ACTION_COMPLETE_MILESTONE,
    NEXT_ACTION_CONTINUE_INTERNAL,
    NEXT_ACTION_GENERATE_HANDOFF,
    NEXT_ACTION_HARD_STOP,
    NEXT_ACTION_REQUIRE_OPERATOR_APPROVAL,
    NEXT_ACTION_REQUIRE_OPERATOR_DECISION,
    NEXT_ACTION_SESSION_TRANSFER,
    NEXT_ACTION_START_NEXT_MILESTONE,
    NEXT_ACTION_USER_REQUESTED_EXPORT,
    NextActionDecision,
    _mapping,
    _sequence,
    _text,
    _truthy,
)

__all__ = [
    "ALLOWED_HANDOFF_REASONS",
    "DEFAULT_PAUSED_EXTERNAL_PROJECTS",
    "HANDOFF_REASON_ARTIFACT_LIFECYCLE_REQUIRED",
    "HANDOFF_REASON_BY_STEP_TYPE",
    "HANDOFF_REASON_COMMIT_REQUIRED",
    "HANDOFF_REASON_CONTEXT_TRANSFER",
    "HANDOFF_REASON_DATABASE_MUTATION_REQUIRED",
    "HANDOFF_REASON_DDL_DML_REQUIRED",
    "HANDOFF_REASON_EXTERNAL_RESUME_REQUIRED",
    "HANDOFF_REASON_FAILED_VALIDATION",
    "HANDOFF_REASON_HARD_BLOCKER",
    "HANDOFF_REASON_MATERIAL_RISK_BOUNDARY",
    "HANDOFF_REASON_MIGRATION_REQUIRED",
    "HANDOFF_REASON_MILESTONE_COMPLETION",
    "HANDOFF_REASON_NONE",
    "HANDOFF_REASON_OPERATOR_APPROVAL",
    "HANDOFF_REASON_OPERATOR_DECISION",
    "HANDOFF_REASON_PACKAGE_REQUIRED",
    "HANDOFF_REASON_PAUSE_RESUME",
    "HANDOFF_REASON_PUSH_DEPLOY_REQUIRED",
    "HANDOFF_REASON_ROLLBACK_UNCERTAINTY",
    "HANDOFF_REASON_RUNTIME_VALIDATION_REQUIRED",
    "HANDOFF_REASON_SECRET_REQUIRED",
    "HANDOFF_REASON_SESSION_TRANSFER",
    "HANDOFF_REASON_USER_EXPORT",
    "INVALID_HANDOFF_REASONS",
    "LOW_RISK_STEP_TYPES",
    "MATERIAL_RISK_STEP_TYPES",
    "NEXT_ACTIONS",
    "NEXT_ACTION_COMPLETE_MILESTONE",
    "NEXT_ACTION_CONTINUE_INTERNAL",
    "NEXT_ACTION_GENERATE_HANDOFF",
    "NEXT_ACTION_HARD_STOP",
    "NEXT_ACTION_REQUIRE_OPERATOR_APPROVAL",
    "NEXT_ACTION_REQUIRE_OPERATOR_DECISION",
    "NEXT_ACTION_SESSION_TRANSFER",
    "NEXT_ACTION_START_NEXT_MILESTONE",
    "NEXT_ACTION_USER_REQUESTED_EXPORT",
    "NextActionDecision",
    "_first_pending_step",
    "_handoff_reason_for_step_type",
    "_is_external_project_work",
    "_is_low_risk_auto_continue",
    "_mapping",
    "_milestone_complete",
    "_milestone_completion_requires_handoff",
    "_requires_operator_approval",
    "_sequence",
    "_stage_gate_block",
    "_step_id",
    "_step_type",
    "_text",
    "_truthy",
    "classify_next_action",
    "handoff_required_for_decision",
    "validate_authority_pack",
    "validate_milestone_completion_criteria",
]
