"""WO-P20-TOOL-TARGETS T2/T3: `ds integrate install <tool>` supports new targets."""

from __future__ import annotations

import sys
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[2]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))


def test_integrate_install_supports_new_tools(tmp_path, monkeypatch):
    """`ds integrate install codex --execute` writes AGENTS.md to the project root."""
    from interfaces.cli.ds import main as ds_main

    monkeypatch.chdir(tmp_path)
    rc = ds_main(["integrate", "install", "codex", "--execute"])
    assert rc == 0
    written = tmp_path / "AGENTS.md"
    assert written.is_file(), "codex install must write AGENTS.md to the project root"
    assert "Pack-Based Routing" in written.read_text(encoding="utf-8")


def test_install_requires_mode(tmp_path, monkeypatch):
    """Without --dry-run/--execute the install refuses (nonzero, writes nothing)."""
    from interfaces.cli.ds import main as ds_main

    monkeypatch.chdir(tmp_path)
    rc = ds_main(["integrate", "install", "codex"])
    assert rc != 0, "install without a mode flag must refuse"
    assert not (tmp_path / "AGENTS.md").exists()


def test_detect_all_includes_new_targets():
    from integrations.detector import detect_all

    ids = {t.tool_id for t in detect_all()}
    for expected in ("claude_code", "codex", "gemini_cli", "windsurf", "aider", "cursor"):
        assert expected in ids, f"detect_all missing {expected}"


def test_end_to_end(tmp_path, monkeypatch):
    """Dry-run writes nothing; execute writes; every project-scoped tool lands AGENTS.md."""
    from interfaces.cli.ds import main as ds_main

    monkeypatch.chdir(tmp_path)

    # Dry run: no file.
    assert ds_main(["integrate", "install", "windsurf", "--dry-run"]) == 0
    assert not (tmp_path / "AGENTS.md").exists()

    # Execute each project-root tool → AGENTS.md present and current.
    for tool in ("codex", "gemini_cli", "windsurf", "aider"):
        (tmp_path / "AGENTS.md").unlink(missing_ok=True)
        assert ds_main(["integrate", "install", tool, "--execute"]) == 0
        out = tmp_path / "AGENTS.md"
        assert out.is_file(), f"{tool}: AGENTS.md missing"
        text = out.read_text(encoding="utf-8")
        assert "GENERATED by integrations/compiler/agents_md.py" in text
        assert "## Work Order Types" in text
