"""AGENTS.md generator — the canonical, GENERATED universal agent target (Phase 20).

AGENTS.md is the tool-agnostic instruction file that any coding agent (Codex,
Cursor, Gemini, Aider, …) reads. It is GENERATED from Dream Studio canonical
sources so it cannot drift from the real routing table / work-order types / gates:

- routing table  ← packs.yaml + canonical skill metadata (reuses the Claude-Code
  compiler's table builder, so both targets stay byte-identical in routing)
- work-order types ← the canonical 10-type set (canonical/skills/ds-project)
- gate definitions ← the canonical close/milestone gates (canonical/skills/ds-workorder)

Tool-specific files (CLAUDE.md, etc.) reduce to a thin adapter that imports this
file plus only their tool-specific extras. ``check_agents_md_fresh`` powers the
drift gate that flags a stale committed AGENTS.md.
"""

from __future__ import annotations

import argparse
from pathlib import Path

from integrations.compiler.claude_code import _build_routing_table

_COMPILER_DIR = Path(__file__).resolve().parent
_REPO_ROOT = _COMPILER_DIR.parent.parent
_PACKS_YAML = _REPO_ROOT / "packs.yaml"
_CANONICAL = _REPO_ROOT / "canonical"
_AGENTS_MD = _REPO_ROOT / "AGENTS.md"

_GENERATED_NOTICE = (
    "<!-- GENERATED by integrations/compiler/agents_md.py — DO NOT EDIT BY HAND.\n"
    "     Regenerate with: py -m integrations.compiler.agents_md --write\n"
    "     Source of truth: packs.yaml + canonical/skills + canonical/workflows. -->"
)

_HEADER = """\
# Dream Studio — Universal Agent Instructions

Dream Studio is a local-first AI orchestration and operational intelligence
platform. This file is a generated projection of Dream Studio authority; any
coding agent (Codex, Cursor, Gemini, Aider, Claude Code, …) is an *adapter
surface* — it does not own Dream Studio authority. Canonical state lives in the
repo source, the operator-local SQLite authority database, and evidence records.
Dashboard output is derived; private model memory is not authority.

Projection source:
- `sqlite:adapter_authority_profiles`, `sqlite:shared_context_packets`
- `repo:canonical/skills/`, `repo:canonical/workflows/`, `repo:packs.yaml`
- file-backed evidence under the operator-local Dream Studio meta store

When the user's intent matches a Dream Studio skill, invoke that skill before any
built-in behavior. Match on the routing keywords below.
"""

# Canonical 10 work-order types — mirrors canonical/skills/ds-project/SKILL.md.
_WO_TYPES: list[tuple[str, str]] = [
    ("ui_component", "Building a reusable UI element (button, card, modal, chart)"),
    ("ui_page", "Building a complete screen/view with navigation and layout"),
    ("api_endpoint", "Adding or modifying a backend route, including request/response contract"),
    ("authentication", "Implementing login, session management, OAuth, or token handling"),
    ("saas_feature", "A user-facing product capability that spans UI + API (e.g., billing)"),
    ("data_pipeline", "ETL, ingestion, transformation, or batch processing work"),
    ("game_mechanic", "A gameplay rule, interaction system, or physics behavior"),
    ("deployment", "CI/CD pipeline, containerization, infrastructure-as-code, release automation"),
    ("infrastructure", "Database schema, cloud resource provisioning, network configuration"),
    ("documentation", "Technical specs, API references, architecture decision records"),
]

# Canonical close/milestone gates — mirrors canonical/skills/ds-workorder + core.work_orders.close.
_GATES: list[tuple[str, str]] = [
    ("tasks_done", "Every task on the work order must be marked done — no 0/N closes."),
    ("design_brief_locked", "UI work orders require a locked design brief (ds-project:brief)."),
    (
        "api_contract_exists",
        "API work orders require a written request/response contract artifact.",
    ),
    ("all_tests_pass", "The work order's TEST-CHECK acceptance criteria must pass."),
    (
        "independent_review",
        "A passing review-verdict.json (ds work-order verify) — mandatory for escalated WOs.",
    ),
    ("design_critique", "Milestone close: website:critique design audit (score ≥ 3)."),
    ("security_scan", "Milestone close: security audit with no BLOCKED findings."),
    ("hardening", "Milestone close: quality:harden results containing PASSED."),
]

_AUTHORITY_RULES = """\
## Authority & Operating Rules

- **Before any work:** invoke `ds-project:resume` (calls `get_project_state()`),
  then `start_work_order(work_order_id=…)`. Working without it is working blind.
- **Tasks live in SQLite, not docs.** Read the work order's task list and
  acceptance criteria from the authority (`ds work-order tasks <id>`). The
  `.planning/` files are reference only — never the execution source of truth.
- **During work:** stay within the work order's `module_boundary`; complete tasks
  in order via `mark_task_done(...)`.
- **Before finishing:** `close_work_order(...)`. Gates must pass; never
  `force=True` without explicit operator approval.
- **No fabricated data, no false-done.** Every discovered defect is registered as
  a work order in the authority (not a GitHub-issue-only or PR-note).

## Output Discipline

Write every file to exactly one of three locations — diagnostic output at the
repo root is forbidden:
- **Type 1 — repo-internal working state:** `<repo>/.planning/<subdir>/`
- **Type 2 — project workspace:** `~/.dream-studio/projects/<project-id>/`
- **Type 3 — session diagnostics:** `~/.dream-studio/diagnostics/<YYYY-MM-DD>/<repo>/<purpose>/`
"""


def _wo_types_section() -> str:
    rows = "\n".join(f"| `{name}` | {desc} |" for name, desc in _WO_TYPES)
    return "## Work Order Types\n\n" "| Type | Use when |\n|------|----------|\n" + rows + "\n"


def _gates_section() -> str:
    rows = "\n".join(f"| `{name}` | {desc} |" for name, desc in _GATES)
    return (
        "## Gate Definitions\n\n"
        "Close is blocked until these pass (preview with `check_close_gates`):\n\n"
        "| Gate | Requirement |\n|------|-------------|\n" + rows + "\n"
    )


def build_agents_md(
    canonical_root: Path | None = None,
    packs_yaml_path: Path | None = None,
) -> str:
    """Assemble the full, deterministic AGENTS.md content from canonical sources."""
    root = canonical_root if canonical_root is not None else _CANONICAL
    packs = packs_yaml_path if packs_yaml_path is not None else _PACKS_YAML

    routing_table = _build_routing_table(root, packs)

    sections = [
        _GENERATED_NOTICE,
        _HEADER.rstrip(),
        "## Skill Routing\n\n" + routing_table.rstrip(),
        _wo_types_section().rstrip(),
        _gates_section().rstrip(),
        _AUTHORITY_RULES.rstrip(),
    ]
    return "\n\n".join(sections).rstrip() + "\n"


def write_agents_md(output_path: Path | None = None) -> Path:
    """Generate and write AGENTS.md. Returns the written path."""
    out = output_path if output_path is not None else _AGENTS_MD
    out.write_text(build_agents_md(), encoding="utf-8")
    return out


def check_agents_md_fresh(agents_md_path: Path | None = None) -> dict:
    """Compare the committed AGENTS.md to freshly generated content.

    Returns {"ok": bool, "stale": bool, "exists": bool, "reason": str}. ok=False
    when the file is missing or stale — the drift gate fails on ok=False.
    """
    path = agents_md_path if agents_md_path is not None else _AGENTS_MD
    expected = build_agents_md()
    if not path.is_file():
        return {
            "ok": False,
            "stale": True,
            "exists": False,
            "reason": "AGENTS.md missing — run: py -m integrations.compiler.agents_md --write",
        }
    actual = path.read_text(encoding="utf-8")
    if actual != expected:
        return {
            "ok": False,
            "stale": True,
            "exists": True,
            "reason": (
                "AGENTS.md is stale vs canonical skills/workflows/packs — "
                "regenerate: py -m integrations.compiler.agents_md --write"
            ),
        }
    return {"ok": True, "stale": False, "exists": True, "reason": "AGENTS.md is current"}


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Generate or check AGENTS.md")
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--write", action="store_true", help="(re)generate AGENTS.md")
    group.add_argument("--check", action="store_true", help="fail if AGENTS.md is stale/missing")
    args = parser.parse_args(argv)

    if args.write:
        out = write_agents_md()
        print(f"AGENTS.md written: {out}")
        return 0
    result = check_agents_md_fresh()
    print(result["reason"])
    return 0 if result["ok"] else 1


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
