"""AGENTS.md generators — TWO files with the same name and different readers.

``build_agents_md`` — the OPERATOR projection the installer ships beside the
generated ``~/.claude/CLAUDE.md``, whose ``@AGENTS.md`` import resolves to it.
Generated from canonical sources so it cannot drift from the real routing:

- routing table  ← packs.yaml + canonical skill metadata (reuses the Claude-Code
  compiler's table builder, so both targets stay byte-identical in routing)
- work-order types ← the canonical 10-type set (canonical/skills/ds-project)
- gate definitions ← the canonical close/milestone gates (canonical/skills/ds-workorder)

``build_repo_agents_md`` — the CONTRIBUTOR file committed at the repository root,
read by an agent working ON this codebase. It carries none of the above.

THEY WERE ONE FUNCTION UNTIL 2026-09-21, and that conflation was the bug. The
repo-root file is loaded automatically by any agent opening this directory, so
its routing table reached every session here — including sessions with Dream
Studio uninstalled, where it named 13 skills, a SQLite authority and blocking
hooks that did not exist. Nobody installing the product ever reads it: the
product ships from ``dist/plugin``, which contains neither AGENTS.md nor
CLAUDE.md. So the operator content was a drifting duplicate when installed and a
pointer at nothing when not.

Trimming the repo copy while they shared one function stripped routing out of
every fresh install, which is why they are separate now and why
``check_agents_md_fresh`` compares the committed file against the REPO builder.
"""

from __future__ import annotations

import argparse
from pathlib import Path

from integrations.compiler.claude_code import _build_routing_table

_COMPILER_DIR = Path(__file__).resolve().parent
_REPO_ROOT = _COMPILER_DIR.parent.parent
_PACKS_YAML = _REPO_ROOT / "packs.yaml"
_CANONICAL = _REPO_ROOT / "canonical"
_AGENTS_MD = _REPO_ROOT / "AGENTS.md"

_GENERATED_NOTICE = (
    "<!-- GENERATED by integrations/compiler/agents_md.py — DO NOT EDIT BY HAND.\n"
    "     Regenerate with: py -m integrations.compiler.agents_md --write\n"
    "     Source of truth: packs.yaml + canonical/skills + canonical/workflows. -->"
)

#: Header for the OPERATOR projection the installer ships (`build_agents_md`).
#: Unchanged -- an installed Dream Studio genuinely is what this describes.
_OPERATOR_HEADER = """\
# Dream Studio — Universal Agent Instructions

Dream Studio is a local-first AI orchestration and operational intelligence
platform. This file is a generated projection of Dream Studio authority; any
coding agent (Codex, Cursor, Gemini, Aider, Claude Code, …) is an *adapter
surface* — it does not own Dream Studio authority. Canonical state lives in the
repo source, the operator-local SQLite authority database, and evidence records.
Dashboard output is derived; private model memory is not authority.

Projection source:
- `sqlite:adapter_authority_profiles`, `sqlite:shared_context_packets`
- `repo:canonical/skills/`, `repo:canonical/workflows/`, `repo:packs.yaml`
- file-backed evidence under the operator-local Dream Studio meta store

When the user's intent matches a Dream Studio skill, invoke that skill before any
built-in behavior. Match on the routing keywords below.
"""

#: Header for the CONTRIBUTOR file at the repository root (`build_repo_agents_md`).
_HEADER = """\
# dream-studio — Universal Agent Instructions

Instructions for any coding agent (Codex, Cursor, Gemini, Aider, Claude Code, …)
working **on** this repository. `CLAUDE.md` carries the same guidance for Claude
Code, which reads that file automatically.

This file used to carry the Dream Studio skill-routing table, the work-order
types and the close gates — about ninety lines describing how to OPERATE an
installed Dream Studio. That is gone, deliberately, for the same reason it left
CLAUDE.md:

- **Nobody installing Dream Studio reads this file.** The product ships from
  `dist/plugin`, which contains neither this nor `CLAUDE.md`.
- **With Dream Studio installed** it duplicated the projection the installer
  writes to the operator's home directory, and drifted from it.
- **Without it installed** it routed every session at skills, an authority
  database and blocking hooks that do not exist — which is what happened after an
  uninstall on 2026-09-21. It survived that uninstall because it is checked into
  git, and kept steering work at a runtime that had been removed.

Operator instructions belong in the projection the installer writes and the
uninstaller removes. This file is about the repository.
"""

_CONTRIBUTING = """\
## Running tests

Pytest output on Windows can be UTF-16-encoded and report a misleading exit code.
Redirect to a file and read that back — the summary line is authoritative, the
exit code is not:

```
py -m pytest <args> > out.txt 2>&1
```

The full unit suite takes roughly 35 minutes on Windows and does not OOM
(6,044 passed / 25 failed, measured 2026-09-21).

## Gates

The repository's own quality gates are declared in
`canonical/workflows/pre-push.yaml` and run with `py -m core.gates.pre_push`.
They are ordinary Python and need no Dream Studio install.

## Before and after a source edit

- Read the git history first. Something that looks missing is often a deliberate
  deletion: `git log --diff-filter=D -- <path>`.
- Check whether a file is GENERATED before editing it. Several checked-in
  artifacts are, including this one, `canonical/review_lanes.yml`,
  `canonical/rules.yml` and everything under `dist/plugin/`. Edit the generator —
  an edit to the artifact is discarded by the next render.
- After the change, validate imports, public API and route contracts, read-model
  shapes, and anything reading a SQLite boundary that moved.

## Commits and pull requests

- Never add AI attribution to a commit or a PR body. Never use emoji.
- One logical change per commit; explain why, not what.
- Keep mechanical formatting in its own commit.
- Never push directly to `main` — branch first.
- Write scratch output to a temp directory, never the repository root.
"""

# Canonical 10 work-order types — mirrors canonical/skills/ds-project/SKILL.md.
_WO_TYPES: list[tuple[str, str]] = [
    ("ui_component", "Building a reusable UI element (button, card, modal, chart)"),
    ("ui_page", "Building a complete screen/view with navigation and layout"),
    ("api_endpoint", "Adding or modifying a backend route, including request/response contract"),
    ("authentication", "Implementing login, session management, OAuth, or token handling"),
    ("saas_feature", "A user-facing product capability that spans UI + API (e.g., billing)"),
    ("data_pipeline", "ETL, ingestion, transformation, or batch processing work"),
    ("game_mechanic", "A gameplay rule, interaction system, or physics behavior"),
    ("deployment", "CI/CD pipeline, containerization, infrastructure-as-code, release automation"),
    ("infrastructure", "Database schema, cloud resource provisioning, network configuration"),
    ("documentation", "Technical specs, API references, architecture decision records"),
]

# Canonical close/milestone gates — mirrors canonical/skills/ds-workorder + core.work_orders.close.
_GATES: list[tuple[str, str]] = [
    ("tasks_done", "Every task on the work order must be marked done — no 0/N closes."),
    ("design_brief_locked", "UI work orders require a locked design brief (ds-project:brief)."),
    (
        "api_contract_exists",
        "API work orders require a written request/response contract artifact.",
    ),
    ("all_tests_pass", "The work order's TEST-CHECK acceptance criteria must pass."),
    (
        "independent_review",
        "A passing review-verdict.json (ds work-order verify) — mandatory for escalated WOs.",
    ),
    ("design_critique", "Milestone close: website:critique design audit (score ≥ 3)."),
    ("security_scan", "Milestone close: security audit with no BLOCKED findings."),
    ("hardening", "Milestone close: quality:harden results containing PASSED."),
]

_AUTHORITY_RULES = """\
## Authority & Operating Rules

- **Before any work:** `ds project state` (where the work stands), then
  `ds work-order start <id>`. Working without it is working blind.
- **Tasks live in SQLite, not docs.** Read the work order's task list and
  acceptance criteria from the authority (`ds work-order tasks <id>`). The
  `.planning` docstore entries are reference only — never the execution source of truth.
- **During work:** stay within the work order's `module_boundary`; start a task with
  `ds work-order task-start <wo> <task>` and finish it with `ds work-order task-done`.
- **Before finishing:** `ds work-order close <id>`. Gates must pass; never `--force`
  without explicit operator approval, and a forced close is recorded.
- **No fabricated data, no false-done.** Every discovered defect is registered as
  a work order in the authority (not a GitHub-issue-only or PR-note).

## Output Discipline

Write output to exactly one of three homes — diagnostic output at the repo root is
forbidden, and `.planning` on disk is forbidden (denied by the on-edit enforcement hook):
- **Type 1 — repo-internal working state:** the files.db docstore, NOT disk. Author with
  `ds files write "<name>" --category planning` (read `ds files read "<name>"`; list
  `ds files list --category planning`). Use the former `.planning/<subdir>/` path as the
  logical name prefix, e.g. `workstreams/<id>/pr-body.md`, `audits/<name>.md`.
- **Type 2 — project workspace:** `~/.dream-studio/projects/<project-id>/`
- **Type 3 — session diagnostics:** `~/.dream-studio/diagnostics/<YYYY-MM-DD>/<repo>/<purpose>/`
"""


def _wo_types_section() -> str:
    rows = "\n".join(f"| `{name}` | {desc} |" for name, desc in _WO_TYPES)
    return "## Work Order Types\n\n" "| Type | Use when |\n|------|----------|\n" + rows + "\n"


def _gates_section() -> str:
    rows = "\n".join(f"| `{name}` | {desc} |" for name, desc in _GATES)
    return (
        "## Gate Definitions\n\n"
        "Close is blocked until these pass (preview with `check_close_gates`):\n\n"
        "| Gate | Requirement |\n|------|-------------|\n" + rows + "\n"
    )


#: The registry lives at canonical/rules.yml, which `dist/plugin` does not ship.
_RULES_YAML = _REPO_ROOT / "canonical" / "rules.yml"


def _rules_section(rules_path: Path | None = None) -> str:
    """The guidance rules, projected into what an install receives.

    ONLY THE GUIDANCE ONES. A rule with `enforced_by` does not need to be read: the gate
    refuses and the refusal names what objected. A rule declared `guidance` is one no
    check can settle -- an instruction to the model, answerable only by an eval -- so an
    agent that never receives it simply does not follow it. Those are the ones that have
    to travel, and until the three lifecycle packs were dissolved they travelled as skill
    text.

    Projecting all 56 would put the registry in every session's context to restate what
    the code already does, which is the context cost the dissolution exists to remove.

    An unreadable or absent registry yields an EMPTY STRING rather than a stub heading: a
    section that says "Operating Rules" and lists nothing reads as "there are none",
    which is worse than the section being absent and noticed.
    """
    import yaml

    path = rules_path if rules_path is not None else _RULES_YAML
    try:
        data = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    except (OSError, ValueError):
        return ""
    rules = [r for r in (data.get("rules") or []) if isinstance(r, dict)]
    guidance = [r for r in rules if r.get("guidance") is True]
    if not guidance:
        return ""

    lines = [
        "## Operating Rules",
        "",
        "These are the rules **nothing enforces**. Every other rule in Dream Studio is held",
        "up by a gate that refuses and says what objected; these cannot be, so following",
        "them is yours to do.",
        "",
    ]
    for rule in sorted(guidance, key=lambda r: str(r.get("id", ""))):
        statement = " ".join(str(rule.get("statement", "")).split())
        if statement:
            lines.append(f"- {statement}")
    return "\n".join(lines) + "\n"


def build_agents_md(
    canonical_root: Path | None = None,
    packs_yaml_path: Path | None = None,
) -> str:
    """The OPERATOR projection: routing, work-order types and close gates.

    This is what the installer ships beside the generated `~/.claude/CLAUDE.md`,
    whose `@AGENTS.md` import resolves to it. It must keep the routing table: an
    install with the skills present and nothing routing to them is an install that
    does nothing.

    NOT what the repository root carries -- see `build_repo_agents_md`. The two
    were one function until 2026-09-21, and collapsing them meant trimming the
    repo copy silently stripped routing out of every fresh install.
    """
    root = canonical_root if canonical_root is not None else _CANONICAL
    packs = packs_yaml_path if packs_yaml_path is not None else _PACKS_YAML

    routing_table = _build_routing_table(root, packs)

    sections = [
        _GENERATED_NOTICE,
        _OPERATOR_HEADER.rstrip(),
        "## Skill Routing\n\n" + routing_table.rstrip(),
        _wo_types_section().rstrip(),
        _gates_section().rstrip(),
        _AUTHORITY_RULES.rstrip(),
        # The guidance rules, which reach an install through nothing else: the registry
        # they live in is not shipped, and they are the half no gate can enforce.
        _rules_section().rstrip(),
    ]
    return "\n\n".join(s for s in sections if s).rstrip() + "\n"


def build_repo_agents_md() -> str:
    """The CONTRIBUTOR file committed at the repository root.

    Read by an agent working ON this codebase, never by anyone installing the
    product -- `dist/plugin` ships neither this nor CLAUDE.md. It therefore carries
    no routing table, no work-order types and no close gates: with the product
    installed those duplicated the operator projection and drifted from it, and
    without it they pointed every session at skills, an authority database and
    hooks that were not there.
    """
    return (
        "\n\n".join([_GENERATED_NOTICE, _HEADER.rstrip(), _CONTRIBUTING.rstrip()]).rstrip() + "\n"
    )


def write_agents_md(output_path: Path | None = None) -> Path:
    """Write the repo-root AGENTS.md. Returns the written path."""
    out = output_path if output_path is not None else _AGENTS_MD
    out.write_text(build_repo_agents_md(), encoding="utf-8")
    return out


def check_agents_md_fresh(agents_md_path: Path | None = None) -> dict:
    """Compare the committed AGENTS.md to freshly generated content.

    Returns {"ok": bool, "stale": bool, "exists": bool, "reason": str}. ok=False
    when the file is missing or stale — the drift gate fails on ok=False.
    """
    path = agents_md_path if agents_md_path is not None else _AGENTS_MD
    # The COMMITTED file is the contributor one, so that is what freshness means
    # here. Comparing it to the operator projection would report the repo as
    # permanently stale and tell anyone who ran the drift gate to overwrite the
    # contributor file with a routing table.
    expected = build_repo_agents_md()
    if not path.is_file():
        return {
            "ok": False,
            "stale": True,
            "exists": False,
            "reason": "AGENTS.md missing — run: py -m integrations.compiler.agents_md --write",
        }
    actual = path.read_text(encoding="utf-8")
    if actual != expected:
        return {
            "ok": False,
            "stale": True,
            "exists": True,
            "reason": (
                "AGENTS.md is stale vs canonical skills/workflows/packs — "
                "regenerate: py -m integrations.compiler.agents_md --write"
            ),
        }
    return {"ok": True, "stale": False, "exists": True, "reason": "AGENTS.md is current"}


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Generate or check AGENTS.md")
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--write", action="store_true", help="(re)generate AGENTS.md")
    group.add_argument("--check", action="store_true", help="fail if AGENTS.md is stale/missing")
    args = parser.parse_args(argv)

    if args.write:
        out = write_agents_md()
        print(f"AGENTS.md written: {out}")
        return 0
    result = check_agents_md_fresh()
    print(result["reason"])
    return 0 if result["ok"] else 1


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
