"""Compile a subagent from its declaration and the skill that holds its knowledge.

WHY THE KNOWLEDGE IS INLINED RATHER THAN POINTED AT. Every bundled agent used to be a
persona plus a line reading "your full set of patterns, anti-patterns, gotchas, commands
and version notes is in ~/.claude/skills/<file>. Read it completely before responding."

That is an instruction, not a mechanism. Nothing makes a subagent read the file, and when
it does not, the answer comes from general knowledge -- fluent, confident, and
indistinguishable from a good one. Every agent shipped with a fallback paragraph beginning
"If the skill file is unavailable", which is the authors recording that they knew the
pointer was unreliable. Inlining removes the pointer and the need for the fallback.

Measured before this landed: the nine agents totalled 7,085 bytes and the skills they
pointed at totalled 64,098 -- a mean of 7,122 bytes, roughly 1,780 tokens, per dispatch.
An agent body is a subagent's system prompt and is loaded only when that agent is
dispatched, so the cost is paid once per dispatch and nowhere else. That is a small price
for knowledge being present by construction instead of by compliance.

WHAT THE DECLARATION OWNS AND WHAT THE SKILL OWNS. The `.meta.yml` beside each agent
carries what is true of the WORKER -- its routing description, its model, its scope, its
working rules, and which skill holds its domain. The skill carries the domain knowledge and
stays the single source of truth for it. Neither duplicates the other, and this compiler is
what keeps them from separating: the generated-artifacts gate fails a push where a skill
changed and its agents were not recompiled.

`scope` is optional and deliberately not defaulted. Eight of the nine agents have never
declared one, and inventing boundaries for domains nobody has scoped would be fabricating
authority. `report_unscoped()` counts them instead, so the gap is visible rather than
papered over.
"""

from __future__ import annotations

import sys
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[2]
AGENTS_DIR = REPO_ROOT / "canonical" / "agents"

#: Where an installed agent's skill lives, and therefore where this compiler reads it
#: from. `dist/plugin/skills` is the shipped projection -- the thing an install actually
#: receives -- so compiling from it means the agent carries the text the operator gets.
SHIPPED_SKILLS = REPO_ROOT / "dist" / "plugin" / "skills"

BANNER = (
    "<!-- GENERATED by integrations/compiler/agents.py from {meta} and the skill inlined\n"
    "     below. Do not edit this file: `py -m integrations.compiler.agents --write`\n"
    "     regenerates it, and the generated-artifacts gate fails a push where it drifted. -->"
)

#: The contract every subagent in this repository answers to, stated once. It is derived
#: from the arrangement `canonical/agents/README.md` already documents -- "Skills
#: orchestrate agents; agents do not invoke skills. The skill owns process, gates and
#: artifacts; the agent supplies domain expertise" -- not invented here. A subagent's
#: report is the only thing that survives it, so what it returns is part of its definition.
SHARED_CONTRACT = """## What you return

You are dispatched by a skill that owns the process, the gates and the artifacts. You
supply domain judgement and hand it back; you do not invoke skills, open pull requests, or
decide that the work is finished.

- **Answer the question you were asked**, and say plainly when the answer is "I cannot tell
  from what I was given" — an invented specific is worse than an admitted gap.
- **Cite what you looked at.** A file and line, a command and its output, a version number.
  A claim with no citation reads as fact and nothing downstream questions it.
- **Report what you could not check**, rather than narrowing the question until it fits.
- **Stay inside your scope.** Work that belongs to another domain is handed back by name,
  not attempted."""


COVERAGE = AGENTS_DIR / "coverage.yml"

#: A mode with no override runs on this. Judgement about a domain, not search.
DEFAULT_MODEL = "sonnet"


def _coverage() -> list[dict[str, Any]]:
    """Every mode that declares an agent, from canonical/agents/coverage.yml.

    COVERAGE IS THE SOURCE, not a per-agent file. Fifty-four modes want an agent and
    nine of them have anything agent-specific to say; writing forty-five near-empty
    declarations would be ceremony, and a file that exists only to be empty is one people
    learn to skip reading. The declaration is the coverage row; `<name>.meta.yml` is an
    OPTIONAL overlay for the agents that do have a scope, working rules, or a model of
    their own.
    """
    import yaml

    data = yaml.safe_load(COVERAGE.read_text(encoding="utf-8")) or {}
    rows = []
    for row in data.get("modes") or []:
        if not row.get("agent"):
            continue
        for required in ("description", "installed_skill"):
            if not str(row.get(required) or "").strip():
                raise ValueError(
                    f"coverage.yml: {row.get('mode')} declares an agent but no {required}"
                )
        rows.append(row)
    return sorted(rows, key=lambda r: r["agent"])


def _overlay(name: str) -> dict[str, Any]:
    """Whatever `<name>.meta.yml` adds, or {}. Never required."""
    import yaml

    path = AGENTS_DIR / f"{name}.meta.yml"
    if not path.is_file():
        return {}
    data = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    if not isinstance(data, dict):
        raise ValueError(f"{path.name}: expected a mapping")
    return data


def _load_meta(row: dict[str, Any]) -> dict[str, Any]:
    """The declaration for one agent: its coverage row, plus any overlay."""
    merged = {
        "description": row["description"],
        "skill": row["installed_skill"],
        "model": DEFAULT_MODEL,
        "mode": row["mode"],
    }
    merged.update({k: v for k, v in _overlay(row["agent"]).items() if v})
    return merged


def meta_files() -> list[str]:
    """Agent names, kept under the old name so callers need not change."""
    return [row["agent"] for row in _coverage()]


def build_agent(row: dict[str, Any]) -> str:
    """The full text of the agent file this declaration compiles to."""
    meta = _load_meta(row)
    name = row["agent"]

    skill_path = SHIPPED_SKILLS / str(meta["skill"]).strip()
    if not skill_path.is_file():
        raise FileNotFoundError(
            f"{name}: skill {meta['skill']} is not in the shipped plugin. "
            "Regenerate dist/plugin, or correct the path."
        )
    knowledge = skill_path.read_text(encoding="utf-8").strip()

    description = " ".join(str(meta["description"]).split())
    parts = [
        "---",
        f"name: {name}",
        f"description: {description}",
        f"model: {str(meta['model']).strip()}",
        "---",
        "",
        BANNER.format(meta=f"the {row['mode']} row of coverage.yml"),
        "",
        f"You are the {name.replace('-', ' ')} subagent.",
        "",
    ]

    scope = str(meta.get("scope") or "").strip()
    if scope:
        parts += ["## Scope", "", scope, ""]

    essentials = str(meta.get("essentials") or "").strip()
    if essentials:
        parts += ["## Working rules", "", essentials, ""]

    parts += [SHARED_CONTRACT, ""]
    parts += [
        "---",
        "",
        f"# Domain knowledge — {meta['skill']}",
        "",
        "Inlined at build time, so it is present whether or not you go and read anything.",
        "",
        knowledge,
        "",
    ]
    return "\n".join(parts)


def check() -> list[str]:
    """Agent files whose content differs from what their declaration compiles to."""
    stale: list[str] = []
    for row in _coverage():
        target = AGENTS_DIR / f"{row['agent']}.md"
        if not target.is_file() or target.read_text(encoding="utf-8") != build_agent(row):
            stale.append(f"{row['agent']}.md")
    return stale


def write() -> list[str]:
    written: list[str] = []
    rows = _coverage()
    for row in rows:
        target = AGENTS_DIR / f"{row['agent']}.md"
        expected = build_agent(row)
        if not target.is_file() or target.read_text(encoding="utf-8") != expected:
            target.write_text(expected, encoding="utf-8")
            written.append(f"{row['agent']}.md")

    # A mode that stops declaring an agent must lose it, or the bench keeps a specialist
    # for a skill nobody routes to any more -- the same drift running backwards.
    live = {f"{row['agent']}.md" for row in rows}
    from integrations.compiler.reviewers import PREFIX as _REVIEW_PREFIX

    for orphan in AGENTS_DIR.glob("*.md"):
        if orphan.name in live or orphan.name.startswith(_REVIEW_PREFIX) or orphan.stem == "README":
            continue
        orphan.unlink()
        written.append(f"{orphan.name} (removed)")
    return sorted(written)


def report_unscoped() -> list[str]:
    """Agents that declare no scope.

    NOT AN ERROR, AND NOT DEFAULTED. Writing boundaries for domains nobody has scoped
    would be inventing authority, so the count is reported instead. The review bench is
    the contrast: every reviewer HAS a scope, because canonical/review_lanes.yml already
    records the questions each seat owns, and scope you can read is not scope you invent.
    """
    return [
        row["agent"] for row in _coverage() if not str(_load_meta(row).get("scope") or "").strip()
    ]


def main(argv: list[str] | None = None) -> int:
    args = list(sys.argv[1:] if argv is None else argv)
    if "--write" in args:
        written = write()
        print(
            f"agents: wrote {len(written)} of {len(meta_files())}"
            + (f" ({', '.join(written)})" if written else " (all current)")
        )
    else:
        stale = check()
        if stale:
            print(f"agents: {len(stale)} stale — {', '.join(stale)}")
            print("Run: py -m integrations.compiler.agents --write")
            return 1
        print(f"agents: all {len(meta_files())} match their declarations")

    unscoped = report_unscoped()
    if unscoped:
        print(
            f"\n{len(unscoped)} of {len(meta_files())} declare no scope: " f"{', '.join(unscoped)}"
        )
        print("  A subagent with no boundary is one that cannot hand work back by name.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
