"""Compile a subagent from its declaration and the skill that holds its knowledge.

WHY THE KNOWLEDGE IS INLINED RATHER THAN POINTED AT. Every bundled agent used to be a
persona plus a line reading "your full set of patterns, anti-patterns, gotchas, commands
and version notes is in ~/.claude/skills/<file>. Read it completely before responding."

That is an instruction, not a mechanism. Nothing makes a subagent read the file, and when
it does not, the answer comes from general knowledge -- fluent, confident, and
indistinguishable from a good one. Every agent shipped with a fallback paragraph beginning
"If the skill file is unavailable", which is the authors recording that they knew the
pointer was unreliable. Inlining removes the pointer and the need for the fallback.

Measured before this landed: the nine agents totalled 7,085 bytes and the skills they
pointed at totalled 64,098 -- a mean of 7,122 bytes, roughly 1,780 tokens, per dispatch.
An agent body is a subagent's system prompt and is loaded only when that agent is
dispatched, so the cost is paid once per dispatch and nowhere else. That is a small price
for knowledge being present by construction instead of by compliance.

WHAT THE DECLARATION OWNS AND WHAT THE SKILL OWNS. The `.meta.yml` beside each agent
carries what is true of the WORKER -- its routing description, its model, its scope, its
working rules, and which skill holds its domain. The skill carries the domain knowledge and
stays the single source of truth for it. Neither duplicates the other, and this compiler is
what keeps them from separating: the generated-artifacts gate fails a push where a skill
changed and its agents were not recompiled.

`scope` is optional. A hand-written one wins; otherwise the DERIVED dispatch scope is
rendered -- which mode dispatches this agent, and the named siblings it hands work to,
both read from coverage.yml rather than invented. That floor exists because every agent
body says "work that belongs to another domain is handed back by name" while no agent was
ever shown the names, so the instruction could not be followed. Subject-matter boundaries
are still nobody's to fabricate; `report_unscoped()` counts the agents carrying only the
derived floor, so the gap is visible rather than
papered over.
"""

from __future__ import annotations

import sys
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[2]
AGENTS_DIR = REPO_ROOT / "canonical" / "agents"

#: Where an installed agent's skill lives, and therefore where this compiler reads it
#: from. `dist/plugin/skills` is the shipped projection -- the thing an install actually
#: receives -- so compiling from it means the agent carries the text the operator gets.
SHIPPED_SKILLS = REPO_ROOT / "dist" / "plugin" / "skills"

BANNER = (
    "<!-- GENERATED by integrations/compiler/agents.py from {meta} and the skill inlined\n"
    "     below. Do not edit this file: `py -m integrations.compiler.agents --write`\n"
    "     regenerates it, and the generated-artifacts gate fails a push where it drifted. -->"
)

#: The contract every subagent in this repository answers to, stated once. It is derived
#: from the arrangement `canonical/agents/README.md` already documents -- "Skills
#: orchestrate agents; agents do not invoke skills. The skill owns process, gates and
#: artifacts; the agent supplies domain expertise" -- not invented here. A subagent's
#: report is the only thing that survives it, so what it returns is part of its definition.
SHARED_CONTRACT = """## What you return

You are dispatched by a skill that owns the process, the gates and the artifacts. You
supply domain judgement and hand it back; you do not invoke skills, open pull requests, or
decide that the work is finished.

- **Answer the question you were asked**, and say plainly when the answer is "I cannot tell
  from what I was given" — an invented specific is worse than an admitted gap.
- **Cite what you looked at.** A file and line, a command and its output, a version number.
  A claim with no citation reads as fact and nothing downstream questions it.
- **Report what you could not check**, rather than narrowing the question until it fits.
- **Stay inside your scope.** Work that belongs to another domain is handed back by name,
  not attempted."""


COVERAGE = AGENTS_DIR / "coverage.yml"

#: A mode with no override runs on this. Judgement about a domain, not search.
DEFAULT_MODEL = "sonnet"


def _coverage() -> list[dict[str, Any]]:
    """Every mode that declares an agent, from canonical/agents/coverage.yml.

    COVERAGE IS THE SOURCE, not a per-agent file. Fifty-four modes want an agent and
    nine of them have anything agent-specific to say; writing forty-five near-empty
    declarations would be ceremony, and a file that exists only to be empty is one people
    learn to skip reading. The declaration is the coverage row; `<name>.meta.yml` is an
    OPTIONAL overlay for the agents that do have a scope, working rules, or a model of
    their own.
    """
    import yaml

    data = yaml.safe_load(COVERAGE.read_text(encoding="utf-8")) or {}
    rows = []
    for row in data.get("modes") or []:
        if not row.get("agent"):
            continue
        for required in ("description", "installed_skill"):
            if not str(row.get(required) or "").strip():
                raise ValueError(
                    f"coverage.yml: {row.get('mode')} declares an agent but no {required}"
                )
        rows.append(row)
    return sorted(rows, key=lambda r: r["agent"])


def _overlay(name: str) -> dict[str, Any]:
    """Whatever `<name>.meta.yml` adds, or {}. Never required."""
    import yaml

    path = AGENTS_DIR / f"{name}.meta.yml"
    if not path.is_file():
        return {}
    data = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    if not isinstance(data, dict):
        raise ValueError(f"{path.name}: expected a mapping")
    return data


def _load_meta(row: dict[str, Any]) -> dict[str, Any]:
    """The declaration for one agent: its coverage row, plus any overlay."""
    merged = {
        "description": row["description"],
        "skill": row["installed_skill"],
        "model": DEFAULT_MODEL,
        "mode": row["mode"],
    }
    merged.update({k: v for k, v in _overlay(row["agent"]).items() if v})
    return merged


def meta_files() -> list[str]:
    """Agent names, kept under the old name so callers need not change."""
    return [row["agent"] for row in _coverage()]


def _imported_references(skill_path: Path) -> list[tuple[str, str]]:
    """The sibling documents a skill's own `## Imports` list names, resolved and read.

    A skill's relative import is correct where the skill lives and meaningless from
    `canonical/agents/`, so naming it in a compiled agent is the same pointer-not-content
    problem this compiler was written to remove -- one level down. Resolved against the
    SKILL.md's directory, which is where the author wrote them from.

    Unreadable or missing targets are skipped rather than raised on: a dangling import is
    a defect in that skill, and `instruction-commands` is the gate that reports it. This
    is the compiler, and refusing to build an agent because its skill names one bad path
    would take the whole specialist out over a broken line.
    """
    import re as _re

    body = skill_path.read_text(encoding="utf-8", errors="replace")
    out: list[tuple[str, str]] = []
    seen: set[Path] = set()
    for rel in _re.findall(r"^[-*]\s+(\.\.?/[^\s`]+\.md)", body, _re.MULTILINE):
        target = (skill_path.parent / rel).resolve()
        if target in seen or not target.is_file():
            continue
        seen.add(target)
        try:
            out.append((rel, target.read_text(encoding="utf-8").strip()))
        except OSError:
            continue
    return out


def build_agent(row: dict[str, Any]) -> str:
    """The full text of the agent file this declaration compiles to."""
    meta = _load_meta(row)
    name = row["agent"]

    skill_path = SHIPPED_SKILLS / str(meta["skill"]).strip()
    if not skill_path.is_file():
        raise FileNotFoundError(
            f"{name}: skill {meta['skill']} is not in the shipped plugin. "
            "Regenerate dist/plugin, or correct the path."
        )
    knowledge = skill_path.read_text(encoding="utf-8").strip()

    description = " ".join(str(meta["description"]).split())
    parts = [
        "---",
        f"name: {name}",
        f"description: {description}",
        f"model: {str(meta['model']).strip()}",
        "---",
        "",
        BANNER.format(meta=f"the {row['mode']} row of coverage.yml"),
        "",
        f"You are the {name.replace('-', ' ')} subagent.",
        "",
    ]

    # A hand-written scope wins; otherwise the registry's own answer, which is better
    # than the nothing that 23 of 24 agents shipped with.
    scope = str(meta.get("scope") or "").strip() or derived_scope(row)
    parts += ["## Scope", "", scope, ""]

    essentials = str(meta.get("essentials") or "").strip()
    if essentials:
        parts += ["## Working rules", "", essentials, ""]

    parts += [SHARED_CONTRACT, ""]
    parts += [
        "---",
        "",
        f"# Domain knowledge — {meta['skill']}",
        "",
        "Inlined at build time, so it is present whether or not you go and read anything.",
        "",
        knowledge,
        "",
    ]

    # AND WHAT THE SKILL ITSELF IMPORTS. A skill's `## Imports` list is relative to the
    # skill, so from canonical/agents/ those paths resolve to nothing -- the agent was
    # told to read files it could not reach, which is the pointer-not-content problem
    # this compiler exists to remove, one level down.
    for rel, body in _imported_references(skill_path):
        parts += [
            "---",
            "",
            f"# Imported by that skill — {rel}",
            "",
            body,
            "",
        ]
    return "\n".join(parts)


def check() -> list[str]:
    """Agent files whose content differs from what their declaration compiles to."""
    stale: list[str] = []
    for row in _coverage():
        target = AGENTS_DIR / f"{row['agent']}.md"
        if not target.is_file() or target.read_text(encoding="utf-8") != build_agent(row):
            stale.append(f"{row['agent']}.md")
    return stale


def write() -> list[str]:
    written: list[str] = []
    rows = _coverage()
    for row in rows:
        target = AGENTS_DIR / f"{row['agent']}.md"
        expected = build_agent(row)
        if not target.is_file() or target.read_text(encoding="utf-8") != expected:
            target.write_text(expected, encoding="utf-8")
            written.append(f"{row['agent']}.md")

    # A mode that stops declaring an agent must lose it, or the bench keeps a specialist
    # for a skill nobody routes to any more -- the same drift running backwards.
    live = {f"{row['agent']}.md" for row in rows}
    from integrations.compiler.reviewers import PREFIX as _REVIEW_PREFIX

    for orphan in AGENTS_DIR.glob("*.md"):
        if orphan.name in live or orphan.name.startswith(_REVIEW_PREFIX) or orphan.stem == "README":
            continue
        orphan.unlink()
        written.append(f"{orphan.name} (removed)")
    return sorted(written)


def _pack_of(mode: str) -> str:
    return mode.split("/", 1)[0]


def derived_scope(row: dict, rows: list[dict] | None = None) -> str:
    """The dispatch boundary this agent already has, read rather than invented.

    WHAT THIS IS NOT. It is not a statement of subject-matter expertise. Writing that
    for a domain nobody has scoped would be fabricating authority, which is why `scope`
    was left undefaulted and merely counted. This says the two things the registry
    already knows: WHICH MODE this agent is dispatched for, and WHICH NAMED SIBLINGS
    exist to hand work to.

    WHY IT IS WORTH SAYING. Every agent body carries "Stay inside your scope. Work that
    belongs to another domain is handed back by name" -- an instruction that cannot be
    followed, because a subagent sees one skill and has no way to learn the names. It
    was told to name a neighbour it had never been shown. 23 of 24 agents shipped that
    way. Naming the siblings turns the sentence into something obeyable.

    A hand-written `scope:` in `.meta.yml` WINS. An author who has thought about the
    boundary knows more than the registry does; this is the floor, not a ceiling.
    """
    rows = rows if rows is not None else _coverage()
    pack = _pack_of(row["mode"])
    siblings = sorted(
        {r["agent"] for r in rows if _pack_of(r["mode"]) == pack and r["agent"] != row["agent"]}
    )
    lines = [
        f"You are dispatched for **`{row['mode']}`**, and your domain knowledge below is"
        f" that mode's skill. Work outside it is not yours to do.",
    ]
    if siblings:
        lines += [
            "",
            f"The other `{pack}` specialists, so you can hand work back BY NAME rather than"
            " attempting it or returning a vague refusal:",
            "",
        ] + [f"- `{name}`" for name in siblings] + [
            "",
            "This roster reflects coverage.yml's current pack membership. A specialist that"
            " has moved to a different pack is no longer named here by this mechanism --"
            " hand its kind of work back as outside this pack rather than assuming it has"
            " no home.",
        ]
    else:
        lines += [
            "",
            f"You are the only `{pack}` specialist. Work belonging to another pack goes back"
            " to the caller, named as outside this pack rather than attempted.",
        ]
    return "\n".join(lines)


def report_unscoped() -> list[str]:
    """Agents carrying only the DERIVED dispatch scope, with none written for them.

    Still not an error. Writing subject-matter boundaries for a domain nobody has scoped
    would be inventing authority, and that remains undone -- what changed is that every
    agent now carries the scope the registry CAN answer: which mode dispatches it and
    which named siblings it hands work to. The review bench was always the contrast, and
    the reason is the same one that makes the derivation legitimate: `review_lanes.yml`
    already records the questions each seat owns, and scope you can read is not scope you
    invent. `coverage.yml` records which mode each agent answers for; that is equally
    readable.

    So this counts the agents whose boundary is only the readable floor, for whoever
    writes the richer one.
    """
    return [
        row["agent"] for row in _coverage() if not str(_load_meta(row).get("scope") or "").strip()
    ]


def main(argv: list[str] | None = None) -> int:
    args = list(sys.argv[1:] if argv is None else argv)
    if "--write" in args:
        written = write()
        print(
            f"agents: wrote {len(written)} of {len(meta_files())}"
            + (f" ({', '.join(written)})" if written else " (all current)")
        )
    else:
        stale = check()
        if stale:
            print(f"agents: {len(stale)} stale — {', '.join(stale)}")
            print("Run: py -m integrations.compiler.agents --write")
            return 1
        print(f"agents: all {len(meta_files())} match their declarations")

    unscoped = report_unscoped()
    if unscoped:
        print(
            f"\n{len(unscoped)} of {len(meta_files())} carry only the derived"
            f" dispatch scope: {', '.join(unscoped)}"
        )
        print(
            "  Each knows which mode dispatches it and which siblings to hand work"
            " to. None has a subject-matter boundary written for it, which is still"
            " nobody's to invent from here."
        )
    return 0


if __name__ == "__main__":
    sys.exit(main())
