"""Compile a subagent from its declaration and the skill that holds its knowledge.

WHY THE KNOWLEDGE IS INLINED RATHER THAN POINTED AT. Every bundled agent used to be a
persona plus a line reading "your full set of patterns, anti-patterns, gotchas, commands
and version notes is in ~/.claude/skills/<file>. Read it completely before responding."

That is an instruction, not a mechanism. Nothing makes a subagent read the file, and when
it does not, the answer comes from general knowledge -- fluent, confident, and
indistinguishable from a good one. Every agent shipped with a fallback paragraph beginning
"If the skill file is unavailable", which is the authors recording that they knew the
pointer was unreliable. Inlining removes the pointer and the need for the fallback.

Measured before this landed: the nine agents totalled 7,085 bytes and the skills they
pointed at totalled 64,098 -- a mean of 7,122 bytes, roughly 1,780 tokens, per dispatch.
An agent body is a subagent's system prompt and is loaded only when that agent is
dispatched, so the cost is paid once per dispatch and nowhere else. That is a small price
for knowledge being present by construction instead of by compliance.

WHAT THE DECLARATION OWNS AND WHAT THE SKILL OWNS. The `.meta.yml` beside each agent
carries what is true of the WORKER -- its routing description, its model, its scope, its
working rules, and which skill holds its domain. The skill carries the domain knowledge and
stays the single source of truth for it. Neither duplicates the other, and this compiler is
what keeps them from separating: the generated-artifacts gate fails a push where a skill
changed and its agents were not recompiled.

`scope` is optional and deliberately not defaulted. Eight of the nine agents have never
declared one, and inventing boundaries for domains nobody has scoped would be fabricating
authority. `report_unscoped()` counts them instead, so the gap is visible rather than
papered over.
"""

from __future__ import annotations

import sys
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[2]
AGENTS_DIR = REPO_ROOT / "canonical" / "agents"

#: Where an installed agent's skill lives, and therefore where this compiler reads it
#: from. `dist/plugin/skills` is the shipped projection -- the thing an install actually
#: receives -- so compiling from it means the agent carries the text the operator gets.
SHIPPED_SKILLS = REPO_ROOT / "dist" / "plugin" / "skills"

BANNER = (
    "<!-- GENERATED by integrations/compiler/agents.py from {meta} and the skill inlined\n"
    "     below. Do not edit this file: `py -m integrations.compiler.agents --write`\n"
    "     regenerates it, and the generated-artifacts gate fails a push where it drifted. -->"
)

#: The contract every subagent in this repository answers to, stated once. It is derived
#: from the arrangement `canonical/agents/README.md` already documents -- "Skills
#: orchestrate agents; agents do not invoke skills. The skill owns process, gates and
#: artifacts; the agent supplies domain expertise" -- not invented here. A subagent's
#: report is the only thing that survives it, so what it returns is part of its definition.
SHARED_CONTRACT = """## What you return

You are dispatched by a skill that owns the process, the gates and the artifacts. You
supply domain judgement and hand it back; you do not invoke skills, open pull requests, or
decide that the work is finished.

- **Answer the question you were asked**, and say plainly when the answer is "I cannot tell
  from what I was given" — an invented specific is worse than an admitted gap.
- **Cite what you looked at.** A file and line, a command and its output, a version number.
  A claim with no citation reads as fact and nothing downstream questions it.
- **Report what you could not check**, rather than narrowing the question until it fits.
- **Stay inside your scope.** Work that belongs to another domain is handed back by name,
  not attempted."""


def _load_meta(path: Path) -> dict[str, Any]:
    import yaml

    data = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    if not isinstance(data, dict):
        raise ValueError(f"{path.name}: expected a mapping")
    for required in ("description", "model", "skill"):
        if not str(data.get(required) or "").strip():
            raise ValueError(f"{path.name}: `{required}` is required")
    return data


def meta_files() -> list[Path]:
    return sorted(AGENTS_DIR.glob("*.meta.yml"))


def build_agent(meta_path: Path) -> str:
    """The full text of the agent file this declaration compiles to."""
    meta = _load_meta(meta_path)
    name = meta_path.name[: -len(".meta.yml")]

    skill_path = SHIPPED_SKILLS / str(meta["skill"]).strip()
    if not skill_path.is_file():
        raise FileNotFoundError(
            f"{meta_path.name}: skill {meta['skill']} is not in the shipped plugin. "
            "Regenerate dist/plugin, or correct the path."
        )
    knowledge = skill_path.read_text(encoding="utf-8").strip()

    description = " ".join(str(meta["description"]).split())
    parts = [
        "---",
        f"name: {name}",
        f"description: {description}",
        f"model: {str(meta['model']).strip()}",
        "---",
        "",
        BANNER.format(meta=meta_path.name),
        "",
        f"You are the {name.replace('-', ' ')} subagent.",
        "",
    ]

    scope = str(meta.get("scope") or "").strip()
    if scope:
        parts += ["## Scope", "", scope, ""]

    essentials = str(meta.get("essentials") or "").strip()
    if essentials:
        parts += ["## Working rules", "", essentials, ""]

    parts += [SHARED_CONTRACT, ""]
    parts += [
        "---",
        "",
        f"# Domain knowledge — {meta['skill']}",
        "",
        "Inlined at build time, so it is present whether or not you go and read anything.",
        "",
        knowledge,
        "",
    ]
    return "\n".join(parts)


def check() -> list[str]:
    """Agent files whose content differs from what their declaration compiles to."""
    stale: list[str] = []
    for meta_path in meta_files():
        name = meta_path.name[: -len(".meta.yml")]
        target = AGENTS_DIR / f"{name}.md"
        expected = build_agent(meta_path)
        if not target.is_file() or target.read_text(encoding="utf-8") != expected:
            stale.append(f"{name}.md")
    return stale


def write() -> list[str]:
    written: list[str] = []
    for meta_path in meta_files():
        name = meta_path.name[: -len(".meta.yml")]
        target = AGENTS_DIR / f"{name}.md"
        expected = build_agent(meta_path)
        if not target.is_file() or target.read_text(encoding="utf-8") != expected:
            target.write_text(expected, encoding="utf-8")
            written.append(f"{name}.md")
    return written


def report_unscoped() -> list[str]:
    """Agents that declare no scope.

    NOT AN ERROR, AND NOT DEFAULTED. Eight of nine have never had one, and writing
    boundaries for domains nobody has scoped would be inventing authority. Counting them
    makes the gap visible, which is the most this compiler can honestly do about it.
    """
    out = []
    for meta_path in meta_files():
        meta = _load_meta(meta_path)
        if not str(meta.get("scope") or "").strip():
            out.append(meta_path.name[: -len(".meta.yml")])
    return out


def main(argv: list[str] | None = None) -> int:
    args = list(sys.argv[1:] if argv is None else argv)
    if "--write" in args:
        written = write()
        print(
            f"agents: wrote {len(written)} of {len(meta_files())}"
            + (f" ({', '.join(written)})" if written else " (all current)")
        )
    else:
        stale = check()
        if stale:
            print(f"agents: {len(stale)} stale — {', '.join(stale)}")
            print("Run: py -m integrations.compiler.agents --write")
            return 1
        print(f"agents: all {len(meta_files())} match their declarations")

    unscoped = report_unscoped()
    if unscoped:
        print(
            f"\n{len(unscoped)} of {len(meta_files())} declare no scope: " f"{', '.join(unscoped)}"
        )
        print("  A subagent with no boundary is one that cannot hand work back by name.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
