"""Compile a reviewer subagent from the seat it sits in.

WHAT THIS IS FOR. `canonical/review_lanes.yml` is the bench: 26 lanes across 19 seats, each
lane a repeatable question with the defect signature it catches, a precedent it actually
came from, and the measurement that decided how it is answered. Its own header says why it
exists -- those questions lived in reviewers' heads, and prose is where guidance goes to
die.

NINETEEN OF THE TWENTY-SIX LANES ARE `judgment: true`: no detector, no eval. What the round
table does with them today is print `19 lane(s) need a person` and stop. The seats are
specialists and nothing specialist answers them, so in practice one generalist answers all
nineteen or nobody does.

A judgment lane is precisely what a subagent is for, and the lane already carries
everything such an agent needs to know. So this compiles one reviewer per seat, with that
seat's lanes as its knowledge. Nothing here is authored: the question, signature, precedent,
measurement and standards are rendered from the registry, and a seat's scope IS the set of
questions it owns.

WHAT IT DELIBERATELY DOES NOT DO. A reviewer cannot dispatch itself, and a Python gate
cannot dispatch a subagent -- `core.gates.round_table` is a process, not a harness. The
round table names the reviewer each judgment lane needs; the review skill dispatches it.
That is the Mode B arrangement `canonical/agents/README.md` already describes, made
reachable by giving the seats agents to be.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[2]
LANES = REPO_ROOT / "canonical" / "review_lanes.yml"
AGENTS_DIR = REPO_ROOT / "canonical" / "agents"

#: Reviewer agents are prefixed so they never collide with a domain specialist and so an
#: operator reading ~/.claude/agents/ can see at a glance which bench a file belongs to.
PREFIX = "review-"

BANNER = (
    "<!-- GENERATED by integrations/compiler/reviewers.py from the {seat!r} seat in\n"
    "     canonical/review_lanes.yml. Do not edit: `py -m integrations.compiler.reviewers\n"
    "     --write` regenerates it, and the generated-artifacts gate fails a push where it\n"
    "     drifted. To change what this reviewer asks, change the lane. -->"
)

CONTRACT = """## What you return

One verdict per lane you were given, and nothing else. You are convened by a review that
owns the process and the merge decision; you supply an answer to your own questions and
hand it back.

For each lane, return:

- **`lane`** — its id, exactly as given.
- **`verdict`** — `pass`, `finding`, or `cannot-tell`.
- **`evidence`** — for a finding, the file and line, the command and its output, or the
  quoted text. For `cannot-tell`, what you would have needed. A finding with no evidence is
  an opinion, and this bench exists because opinions do not survive review.
- **`why`** — one or two sentences tying the evidence to the lane's signature.

`cannot-tell` is a first-class answer. Narrowing a question until it fits what you can see
is how a lane stops being asked while still appearing to be answered.

Do not answer a lane you were not given, do not rank the findings, and do not decide
whether the change merges — the chair does that."""


def _slug(seat: str) -> str:
    out = re.sub(r"[^a-z0-9]+", "-", seat.lower()).strip("-")
    return f"{PREFIX}{out}"


def reviewer_for_seat(seat: str) -> str | None:
    """The agent name that answers this seat, or None when the seat has no compiled agent.

    Read by `core.gates.round_table` so its listing can name what to convene instead of
    ending at "needs a person". Returns None rather than a guessed name: a round table
    pointing at an agent that does not exist would be the dangling-instruction shape three
    of this week's gates exist to refuse.
    """
    candidate = AGENTS_DIR / f"{_slug(seat)}.md"
    return _slug(seat) if candidate.is_file() else None


#: The chair is not a reviewer. Its lane asks "what is the single merge recommendation
#: here, and is every finding's severity calibrated against it rather than stated in
#: isolation" -- a question that can only be answered by whoever holds the other verdicts.
#: A subagent sees its own lanes and nothing else, so an agent here would be asked to
#: reconcile findings it was never given. The lane stays on the bench and the round table
#: still prints it; what it does not get is a specialist, because the caller IS the chair.
NOT_A_REVIEWER = frozenset({"Chair and verdict owner"})


def _load_seats() -> dict[str, list[dict[str, Any]]]:
    import yaml

    data = yaml.safe_load(LANES.read_text(encoding="utf-8"))
    lanes = data["lanes"] if isinstance(data, dict) else data
    seats: dict[str, list[dict[str, Any]]] = {}
    for lane in lanes or []:
        seats.setdefault(str(lane.get("seat", "")).strip(), []).append(lane)
    seats.pop("", None)
    for excluded in NOT_A_REVIEWER:
        seats.pop(excluded, None)
    return seats


def seat_names() -> list[str]:
    return sorted(_load_seats())


def _describe(seat: str, lanes: list[dict[str, Any]]) -> str:
    """The routing description. Always in context, so it stays one line.

    Built from the seat's own name and the count and subject of its lanes rather than
    written, because a description that drifts from the lanes it routes to is how the
    wrong reviewer gets convened.
    """
    ids = ", ".join(str(lane.get("id", "")) for lane in lanes[:3])
    more = f", +{len(lanes) - 3} more" if len(lanes) > 3 else ""
    return (
        f"Review seat: {seat}. Asks {len(lanes)} lane(s) of a change set — {ids}{more}. "
        f"Convene during a Dream Studio review when the change set touches this seat's scope."
    )


def build_reviewer(seat: str, lanes: list[dict[str, Any]]) -> str:
    parts = [
        "---",
        f"name: {_slug(seat)}",
        f"description: {_describe(seat, lanes)}",
        # Judgment, not search: every lane here asks the reader to reason about a change
        # set against a signature. The repository's routing rule puts that on sonnet.
        "model: sonnet",
        "---",
        "",
        BANNER.format(seat=seat),
        "",
        f"You are the **{seat}** seat on the Dream Studio review bench.",
        "",
        "## Scope",
        "",
        "Your scope is the lanes below and nothing else. A concern that belongs to another",
        "seat is handed back by name, not absorbed — the bench works because each seat asks",
        "its own question and the chair assembles the answers.",
        "",
        CONTRACT,
        "",
        "---",
        "",
        f"# Your lanes ({len(lanes)})",
        "",
    ]

    for lane in lanes:
        kind = "detector" if lane.get("detector") else ("eval" if lane.get("eval") else "judgment")
        parts += [f"## `{lane.get('id')}`", ""]
        parts += [f"**Ask:** {str(lane.get('question', '')).strip()}", ""]
        if lane.get("signature"):
            parts += [
                f"**The defect looks like:** {str(lane['signature']).strip()}",
                "",
            ]
        if lane.get("precedent"):
            parts += [
                f"**It has happened:** {str(lane['precedent']).strip()}",
                "",
            ]
        if lane.get("standards"):
            standards = lane["standards"]
            named = ", ".join(standards) if isinstance(standards, list) else str(standards)
            parts += [
                f"**Governing standard:** {named}. Argue a finding on the standard, "
                "not on seniority.",
                "",
            ]
        if lane.get("measurement"):
            parts += [
                f"**How this is answered, and why:** {str(lane['measurement']).strip()}",
                "",
            ]
        if kind == "judgment" and lane.get("why"):
            parts += [
                f"**Why no detector:** {str(lane['why']).strip()}",
                "",
            ]
        if kind != "judgment":
            parts += [
                f"**Note:** this lane also has a {kind}. It runs mechanically; you answer "
                "what it cannot — whether the thing it measured is the thing that matters "
                "here.",
                "",
            ]

    return "\n".join(parts)


def check() -> list[str]:
    stale: list[str] = []
    for seat, lanes in _load_seats().items():
        target = AGENTS_DIR / f"{_slug(seat)}.md"
        if not target.is_file() or target.read_text(encoding="utf-8") != build_reviewer(
            seat, lanes
        ):
            stale.append(f"{_slug(seat)}.md")
    return sorted(stale)


def write() -> list[str]:
    written: list[str] = []
    seats = _load_seats()
    for seat, lanes in seats.items():
        target = AGENTS_DIR / f"{_slug(seat)}.md"
        expected = build_reviewer(seat, lanes)
        if not target.is_file() or target.read_text(encoding="utf-8") != expected:
            target.write_text(expected, encoding="utf-8")
            written.append(f"{_slug(seat)}.md")

    # A seat removed from the registry must lose its agent, or the bench grows a reviewer
    # asking a question nobody registered any more -- the drift this compiler exists to stop,
    # running backwards.
    live = {f"{_slug(seat)}.md" for seat in seats}
    for orphan in AGENTS_DIR.glob(f"{PREFIX}*.md"):
        if orphan.name not in live:
            orphan.unlink()
            written.append(f"{orphan.name} (removed)")
    return sorted(written)


def main(argv: list[str] | None = None) -> int:
    args = list(sys.argv[1:] if argv is None else argv)
    seats = _load_seats()
    if "--write" in args:
        written = write()
        print(
            f"reviewers: {len(seats)} seat(s); wrote {len(written)}"
            + (f" ({', '.join(written)})" if written else " (all current)")
        )
        return 0

    stale = check()
    if stale:
        print(f"reviewers: {len(stale)} stale — {', '.join(stale)}")
        print("Run: py -m integrations.compiler.reviewers --write")
        return 1
    judgment = sum(
        1
        for lanes in seats.values()
        for lane in lanes
        if not lane.get("detector") and not lane.get("eval")
    )
    print(
        f"reviewers: all {len(seats)} seats match the registry "
        f"({judgment} judgment lane(s) now have a specialist to answer them)"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
