"""Compile a reviewer subagent from the seat it sits in.

WHAT THIS IS FOR. `canonical/review_lanes.yml` is the bench: 26 lanes across 19 seats, each
lane a repeatable question with the defect signature it catches, a precedent it actually
came from, and the measurement that decided how it is answered. Its own header says why it
exists -- those questions lived in reviewers' heads, and prose is where guidance goes to
die.

NINETEEN OF THE TWENTY-SIX LANES ARE `judgment: true`: no detector, no eval. What the round
table does with them today is print `19 lane(s) need a person` and stop. The seats are
specialists and nothing specialist answers them, so in practice one generalist answers all
nineteen or nobody does.

A judgment lane is precisely what a subagent is for, and the lane already carries
everything such an agent needs to know. So this compiles one reviewer per seat, with that
seat's lanes as its knowledge. Nothing here is authored: the question, signature, precedent,
measurement and standards are rendered from the registry, and a seat's scope IS the set of
questions it owns.

WHAT IT DELIBERATELY DOES NOT DO. A reviewer cannot dispatch itself, and a Python gate
cannot dispatch a subagent -- `core.gates.round_table` is a process, not a harness. The
round table names the reviewer each judgment lane needs; the review skill dispatches it.
That is the Mode B arrangement `canonical/agents/README.md` already describes, made
reachable by giving the seats agents to be.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[2]
LANES = REPO_ROOT / "canonical" / "review_lanes.yml"
AGENTS_DIR = REPO_ROOT / "canonical" / "agents"

#: Reviewer agents are prefixed so they never collide with a domain specialist and so an
#: operator reading ~/.claude/agents/ can see at a glance which bench a file belongs to.
PREFIX = "review-"

#: THE ONE PLACE THIS PATTERN LIVES -- build_reviewer() below is the only writer of a
#: `model:` frontmatter line; every installer that reads or replaces one (Claude Code's
#: own, which uses the alias verbatim with no translation table, and the multitool/
#: codex installers, which translate it through integrations.targets.registry) shares
#: this one regex rather than three copies that could drift the way reviewer_files()'s
#: own docstring describes for its glob.
MODEL_LINE_RE = re.compile(r"^model: (.+)$", re.MULTILINE)


def set_model_alias(body: str, alias: str) -> str:
    """*body*'s `model:` frontmatter line, replaced with *alias* verbatim.

    Raises if there is no `model:` line to replace -- a compiled reviewer with no model
    is a bug in the compiler, not something to install around.
    """
    if not MODEL_LINE_RE.search(body):
        raise ValueError("no `model:` line found in this reviewer's frontmatter to replace")
    return MODEL_LINE_RE.sub(f"model: {alias}", body, count=1)


BANNER = (
    "<!-- GENERATED by integrations/compiler/reviewers.py from the {seat!r} seat in\n"
    "     canonical/review_lanes.yml. Do not edit: `py -m integrations.compiler.reviewers\n"
    "     --write` regenerates it, and the generated-artifacts gate fails a push where it\n"
    "     drifted. To change what this reviewer asks, change the lane. -->"
)

CONTRACT = """## How you answer: by testing

You answer by RUNNING things, not by reading them. That is the whole reason the bench is
lanes rather than hardcoded seats: a seat could claim something was wrong without testing
it. Reading is how you decide what to test; it is never the answer.

The review is dispatched against one commit, and a container image is built from exactly
that commit — no network, no host state, an isolated `HOME` and `DREAM_STUDIO_HOME`.
Test in it with the work order id you were given:

```
ds review --run "python -m pytest tests/unit/test_x.py::test_y -q" --work-order <id>
```

It prints the output and exits with the command's exit code. Mutate, delete or break
anything inside — every run starts from a fresh container. **Never modify the working
tree** to test something; the container is where experiments happen.

- To prove a defect, write the test that fails because of it. It can live inside the
  command: `sh -c` receives it, so `printf '...' > /tmp/t.py && python -m pytest /tmp/t.py -q`
  works.
- The exit code is the whole command's. `cmd | tail` reports `tail`'s, not `cmd`'s — run
  the command plain, or redirect to a file and `cat` it after.

## What you return

One answer per lane you were dispatched, and nothing else, in an object that carries the
**credential** you were handed with your dispatch:

```json
{"credential": "<the credential issued to you>", "lanes": [ ...one answer per lane... ]}
```

The recording door refuses a submission that does not carry the credential issued to the
reviewer it claims to be — one seat cannot answer as another. You are convened by a review
that owns the process and the merge decision; you answer your own questions and hand them
back.

For each lane:

- **`lane`** — its id, exactly as given.
- **`verdict`** — `pass`, `finding`, or `cannot-tell`.
- **`reproduction`** — for `pass` and `finding`: `{"command": "...", "exit_code": N}`, the
  command you ran in the lane container and the exit code you saw. The recording door
  RE-RUNS it in a fresh container and refuses the answer if the exit code differs. A
  finding's reproduction exits non-zero because the defect is there; a pass's exits 0
  because the property held. Without one, the only honest verdict is `cannot-tell`.
- **`evidence`** — for a finding: what the reproduction's output shows, and where the
  defect is (file and line). A finding with no evidence is an opinion.
- **`why`** — one or two sentences tying the evidence to the lane's signature. For
  `cannot-tell`, what you would have needed (in `why` or `evidence`).
- **`check`** — optional, findings only: an executable criterion that will show it fixed
  (`TEST-CHECK: <path>::<node>` against a test file that EXISTS, `SQL-CHECK`,
  `API-CHECK`). It becomes the task's acceptance criterion. Leave it empty when the fix
  needs a test that does not exist yet — the finding still holds the work order open
  either way.
- **`declare`** — optional and rare, findings only: why NO executable check could ever
  decide this finding. The task is then filed as a declared claim instead of a checked
  one. It is not a place for the explanation — that goes in `why`.

`cannot-tell` is a first-class answer. Narrowing a question until it fits what you can
test is how a lane stops being asked while still appearing to be answered.

Do not answer a lane you were not dispatched, do not rank the findings, and do not decide
whether the change merges — the chair does that.

Your answers are recorded against the work order (`ds review --record`) and kept: a lane
you leave out is reported unanswered rather than assumed clean. A finding stays open until
a later round answers that lane `pass` AND the finding's own reproduction, re-run by the
door at the new commit, exits 0 — the test that proved the defect must go green. So write
a finding's reproduction to PASS once the defect is fixed; it will be re-run at later
commits. If an earlier finding's reproduction has gone stale (its harness no longer runs
for reasons unrelated to the defect), give the pass a **`resolves_with`** command instead:
the door runs it at the commit the finding was recorded against, where it must FAIL, and
at this commit, where it must PASS. A test that passes at both resolves nothing. That
proves the test discriminates the fix, not that it tests the defect, so a resolution by
`resolves_with` brings the evidence-referee lane into the next round, and the review does
not clear until that lane has judged it. A
`cannot-tell` never resolves a finding; it is recorded and the finding stays open."""


def _slug(seat: str) -> str:
    out = re.sub(r"[^a-z0-9]+", "-", seat.lower()).strip("-")
    return f"{PREFIX}{out}"


def reviewer_files() -> list[Path]:
    """Every compiled reviewer, in the order `sorted()` gives -- not install order,
    just a stable one so a dry-run plan and a real install name files the same way.

    THE ONE PLACE THIS GLOB LIVES. It used to be defined twice -- once in each
    per-format install module (`specialist_agents_target.py`'s md_frontmatter
    installer, `specialist_agents_codex_target.py`'s TOML one) -- which is the same
    "two sites deciding one fact" shape the round table's own first lane exists to
    catch, found here on the module that compiles the very thing those two glob for.
    """
    return sorted(AGENTS_DIR.glob(f"{PREFIX}*.md"))


def _project_seats(repo_root: Path) -> dict[str, Path]:
    """seat name -> cached reviewer Path, for every seat *repo_root*'s own
    `.ds-review-lanes.yml` marker names -- empty when there's no marker. The per-seat
    cache write goes through `_ensure_project_reviewer_cached`, so a caller that only
    wants to know what's installable (this function) still leaves a fresh, installable
    file behind for each name it returns."""
    from core.gates import review_lane_registry
    from core.work_orders import project_review_lanes

    marker = project_review_lanes.marker_path(repo_root)
    if not marker.is_file():
        return {}
    loaded = project_review_lanes.load_and_validate(
        repo_root, reserved_seats=review_lane_registry.SEATS
    )
    if loaded is None:  # pragma: no cover -- marker.is_file() just confirmed True above
        return {}
    _mode, lanes = loaded
    out: dict[str, Path] = {}
    for seat in group_by_seat(lanes):
        cached = _ensure_project_reviewer_cached(seat, repo_root)
        if cached is not None:
            out[seat] = cached
    return out


def project_reviewer_files(repo_root: Path) -> list[Path]:
    """Every seat compiled from *repo_root*'s own `.ds-review-lanes.yml` marker, cached
    and ready to install -- empty when *repo_root* has no marker. Mirrors
    `reviewer_files()`'s DS-bench glob for a project's own bench, so an installer that
    wants "every reviewer this tree can install" composes the two lists rather than
    special-casing project seats."""
    return [path for _seat, path in sorted(_project_seats(repo_root).items())]


def resolve_agent_names(requested: list[str], *, repo_root: Path | None = None) -> list[Path]:
    """The compiled reviewer files named by *requested*, in the order given.

    Each entry may be a seat name ("Finding integrity", matching `seat_names()`
    exactly) or an agent slug/filename stem ("review-finding-integrity", matching a
    real file directly) -- an operator installing a subset reasons in whichever of
    the two they have in front of them, the seat name from the round table's own
    prose or the slug from a file already on disk, and forcing a translation between
    them onto the caller is how a correct request gets typed wrong.

    *repo_root*, when given, also makes that tree's own project seats (see
    `project_reviewer_files`) resolvable by name or slug, the same as Dream Studio's
    own bench -- so `--agents` can name a project's seat explicitly rather than only
    ever getting it via the unfiltered "install everything" path.

    Raises naming every entry that resolved to nothing, with the seat names and slugs
    actually available, rather than silently installing fewer files than asked for --
    the same failure shape `reviewer_for_seat` and `_lanes` both refuse elsewhere in
    this bench.
    """
    by_slug = {f.stem: f for f in reviewer_files()}
    project_seats = _project_seats(repo_root) if repo_root is not None else {}
    for path in project_seats.values():
        by_slug[path.stem] = path

    resolved: list[Path] = []
    unknown: list[str] = []
    for name in requested:
        if name in project_seats:
            path = project_seats[name]
        else:
            slug = _slug(name) if name in seat_names() else name
            path = by_slug.get(slug)
        if path is None:
            unknown.append(name)
        elif path not in resolved:
            resolved.append(path)
    if unknown:
        raise ValueError(
            f"unknown agent(s)/seat(s): {unknown}. Valid slugs: {sorted(by_slug)}."
            f" Valid seat names: {seat_names() + sorted(project_seats)}"
        )
    return resolved


#: The chair is not a reviewer. Its lane asks "what is the single merge recommendation
#: here, and is every finding's severity calibrated against it rather than stated in
#: isolation" -- a question that can only be answered by whoever holds the other verdicts.
#: A subagent sees its own lanes and nothing else, so an agent here would be asked to
#: reconcile findings it was never given. The lane stays on the bench and the round table
#: still prints it; what it does not get is a specialist, because the caller IS the chair.
NOT_A_REVIEWER = frozenset({"Chair and verdict owner"})


def group_by_seat(lanes: list[dict[str, Any]]) -> dict[str, list[dict[str, Any]]]:
    """The same grouping `_load_seats()` does, over any lane list -- not just Dream
    Studio's own. Used by `_load_seats()` itself, and by a project's own lanes (see
    `_ensure_project_reviewer_cached`), so both feed one grouping function instead of
    two copies that could drift apart."""
    seats: dict[str, list[dict[str, Any]]] = {}
    for lane in lanes:
        seats.setdefault(str(lane.get("seat", "")).strip(), []).append(lane)
    seats.pop("", None)
    for excluded in NOT_A_REVIEWER:
        seats.pop(excluded, None)
    return seats


def _load_seats() -> dict[str, list[dict[str, Any]]]:
    import yaml

    data = yaml.safe_load(LANES.read_text(encoding="utf-8"))
    lanes = data["lanes"] if isinstance(data, dict) else data
    return group_by_seat(lanes or [])


#: Where a tree's own project seats are rendered, relative to that tree's root. Under
#: `.dream-studio/`, not checked into the tree's own repo: `**/.dream-studio/` is
#: already gitignored everywhere (see `core.work_orders.review_rules`'s own note on why
#: a profile file cannot live there), and a project seat's compiled agent is disposable,
#: re-derivable state, never a checked-in artifact -- the same "render fresh at
#: need-time" choice `review_rules.py`'s `resolve_review_rules()`/`render_rules_block()`
#: already made for review rules.
_PROJECT_REVIEWER_CACHE = ("dream-studio-cache", "compiled-agents")


def _ensure_project_reviewer_cached(seat: str, repo_root: Path) -> Path | None:
    """This seat's reviewer, rendered from *repo_root*'s own `.ds-review-lanes.yml` into
    a local cache, if the seat is one of that tree's own (not Dream Studio's).

    Returns the cache path, or None when *repo_root* has no marker, or its marker has no
    lane for this seat (including every one of Dream Studio's own seats -- their
    reviewers come from `AGENTS_DIR`, checked before this is ever called; see
    `reviewer_for_seat`).

    RE-VALIDATES THE MARKER ON EVERY CALL rather than trusting a prior validation. By
    the time `core.gates.round_table.convene()` reaches its per-seat reviewer-naming
    loop it has already validated the same marker once (`_lanes()`'s own merge), so in
    practice this never raises there -- but this function has no way to know it is being
    called from a context that already checked, and a caller that did not (a future
    direct call, a test) must get the real error, not a silent None standing in for one.
    """
    from core.gates import review_lane_registry
    from core.work_orders import project_review_lanes

    marker = project_review_lanes.marker_path(repo_root)
    if not marker.is_file():
        return None
    loaded = project_review_lanes.load_and_validate(
        repo_root, reserved_seats=review_lane_registry.SEATS
    )
    if loaded is None:  # pragma: no cover -- marker.is_file() just confirmed True above
        return None
    _mode, project_lanes = loaded
    lanes = group_by_seat(project_lanes).get(seat)
    if not lanes:
        return None

    rendered = build_reviewer(seat, lanes)
    cache_path = Path(repo_root).joinpath(*_PROJECT_REVIEWER_CACHE, f"{_slug(seat)}.md")
    if not cache_path.is_file() or cache_path.read_text(encoding="utf-8") != rendered:
        cache_path.parent.mkdir(parents=True, exist_ok=True)
        cache_path.write_text(rendered, encoding="utf-8")
    return cache_path


def reviewer_for_seat(seat: str, *, repo_root: Path | None = None) -> str | None:
    """The agent name that answers this seat, or None when the seat has no compiled agent.

    Read by `core.gates.round_table` so its listing can name what to convene instead of
    ending at "needs a person". Returns None rather than a guessed name: a round table
    pointing at an agent that does not exist would be the dangling-instruction shape three
    of this week's gates exist to refuse.

    `repo_root`, when given, is the tree under review -- checked for a project's own
    seat (one that compiled from that tree's `.ds-review-lanes.yml` marker rather than
    Dream Studio's own registry) after `AGENTS_DIR` comes up empty. A project's own seat
    never lands in `AGENTS_DIR` (that directory is generator-checked against
    `scripts/seat_lanes_data.py`, and a project's own seat has no business there); its
    agent is rendered instead into a local cache under the project's own tree -- see
    `_ensure_project_reviewer_cached`.
    """
    slug = _slug(seat)
    if (AGENTS_DIR / f"{slug}.md").is_file():
        return slug
    if repo_root is not None and _ensure_project_reviewer_cached(seat, repo_root) is not None:
        return slug
    return None


def seat_names() -> list[str]:
    return sorted(_load_seats())


def _model_for_seat(seat: str, lanes: list[dict[str, Any]]) -> str:
    """The model this seat's compiled reviewer runs on.

    Read from the registry -- `scripts/seat_lanes_data.py`'s `SEAT_MODELS`, rendered onto
    every lane -- rather than a literal in this compiler. One seat compiles to one
    reviewer, so its lanes must agree on the model; `core/gates/review_lane_registry.py`
    already requires every lane to carry a legal one, and disagreement within one seat
    would mean the registry was hand-edited out of step with its generator. Raising here
    rather than silently picking one is the same choice `seat()` makes for a duplicate
    lane id: a compiler that guessed would hide exactly the drift this field exists to
    surface.
    """
    models = {str(lane.get("model", "")).strip() for lane in lanes}
    if len(models) > 1:
        raise ValueError(
            f"seat {seat!r} has lanes disagreeing on model: {sorted(models)}. One seat"
            " compiles to one reviewer agent, so it can only run on one model -- the"
            " registry and its generator (scripts/seat_lanes_data.py) have drifted."
        )
    (model,) = models
    if not model:
        raise ValueError(f"seat {seat!r} declares no model on any of its lanes")
    return model


def seat_name_for_file(path: Path, *, repo_root: Path | None = None) -> str:
    """The seat name a compiled reviewer file was generated from -- the inverse of
    `_slug()`, so an installer deciding per-seat routing can ask "whose seat is this
    file" without re-parsing its own generated banner comment.

    *repo_root*, when given, also resolves a project seat's own cached file (see
    `_project_seats`) back to its seat name, the same tree `resolve_agent_names`
    already searches by name going the other direction.

    Raises ValueError naming the path for a file that resolves to neither -- not a
    compiled reviewer this function can recognize, same failure shape as
    `resolve_agent_names`' own "unknown agent(s)/seat(s)".
    """
    if repo_root is not None:
        for seat, project_path in _project_seats(repo_root).items():
            if project_path == path:
                return seat
    by_slug = {_slug(name): name for name in seat_names()}
    try:
        return by_slug[path.stem]
    except KeyError as exc:
        raise ValueError(f"{path}: not a known seat's compiled reviewer file") from exc


def resolve_seat_assignment(seat: str, install_target: str) -> tuple[str, str | None, str | None]:
    """(provider, model_override, effort_override) for *seat* when installing onto
    *install_target*.

    No pin on record (core.config.seat_providers): (*install_target*, None, None) --
    the seat compiles onto the tool actually being installed, with whatever model
    _model_for_seat() already resolves for it, untouched by this function.

    A pin on record: the pin's own provider, REPLACING *install_target* -- an installer
    compiling onto a different tool than the pin names is not this seat's assignment
    (the installer decides what to do with that, e.g. skip the seat for the general
    "install everything" pass while still honoring an explicit, by-name request for
    it). model/effort are the pin's own overrides when it set them, else None --
    meaning "whatever this seat already resolves to", since a pin need not repeat
    every field to change one.
    """
    from core.config.seat_providers import get_seat_provider

    pin = get_seat_provider(seat)
    if pin is None:
        return install_target, None, None
    return pin["provider"], pin.get("model"), pin.get("effort")


def _describe(seat: str, lanes: list[dict[str, Any]]) -> str:
    """The routing description. Always in context, so it stays one line.

    Built from the seat's own name and the count and subject of its lanes rather than
    written, because a description that drifts from the lanes it routes to is how the
    wrong reviewer gets convened.
    """
    ids = ", ".join(str(lane.get("id", "")) for lane in lanes[:3])
    more = f", +{len(lanes) - 3} more" if len(lanes) > 3 else ""
    return (
        f"Review seat: {seat}. Asks {len(lanes)} lane(s) of a change set — {ids}{more}. "
        f"Convene during a Dream Studio review when the change set touches this seat's scope."
    )


def build_reviewer(seat: str, lanes: list[dict[str, Any]]) -> str:
    parts = [
        "---",
        f"name: {_slug(seat)}",
        f"description: {_describe(seat, lanes)}",
        # Read from the registry, not written here -- see _model_for_seat. This used to be
        # a literal "model: sonnet" for every seat regardless: a side channel, since the
        # fact lived only in this compiler and could not be looked up, diffed, or set per
        # seat without editing code that builds agents.
        f"model: {_model_for_seat(seat, lanes)}",
        "---",
        "",
        BANNER.format(seat=seat),
        "",
        f"You are the **{seat}** seat on the Dream Studio review bench.",
        "",
        "## Scope",
        "",
        "Your scope is the lanes below and nothing else. A concern that belongs to another",
        "seat is handed back by name, not absorbed — the bench works because each seat asks",
        "its own question and the chair assembles the answers.",
        "",
        CONTRACT,
        "",
        "---",
        "",
        f"# Your lanes ({len(lanes)})",
        "",
    ]

    for lane in lanes:
        kind = "detector" if lane.get("detector") else ("eval" if lane.get("eval") else "judgment")
        parts += [f"## `{lane.get('id')}`", ""]
        parts += [f"**Ask:** {str(lane.get('question', '')).strip()}", ""]
        if lane.get("signature"):
            parts += [
                f"**The defect looks like:** {str(lane['signature']).strip()}",
                "",
            ]
        if lane.get("precedent"):
            parts += [
                f"**It has happened:** {str(lane['precedent']).strip()}",
                "",
            ]
        if lane.get("standards"):
            standards = lane["standards"]
            named = ", ".join(standards) if isinstance(standards, list) else str(standards)
            parts += [
                f"**Governing standard:** {named}. Argue a finding on the standard, "
                "not on seniority.",
                "",
            ]
        if lane.get("measurement"):
            parts += [
                f"**How this is answered, and why:** {str(lane['measurement']).strip()}",
                "",
            ]
        if kind == "judgment" and lane.get("why"):
            parts += [
                f"**Why no detector:** {str(lane['why']).strip()}",
                "",
            ]
        if kind != "judgment":
            parts += [
                f"**Note:** this lane also has a {kind}. It runs mechanically; you answer "
                "what it cannot — whether the thing it measured is the thing that matters "
                "here.",
                "",
            ]

    return "\n".join(parts)


def check() -> list[str]:
    stale: list[str] = []
    for seat, lanes in _load_seats().items():
        target = AGENTS_DIR / f"{_slug(seat)}.md"
        if not target.is_file() or target.read_text(encoding="utf-8") != build_reviewer(
            seat, lanes
        ):
            stale.append(f"{_slug(seat)}.md")
    return sorted(stale)


def write() -> list[str]:
    written: list[str] = []
    seats = _load_seats()
    for seat, lanes in seats.items():
        target = AGENTS_DIR / f"{_slug(seat)}.md"
        expected = build_reviewer(seat, lanes)
        if not target.is_file() or target.read_text(encoding="utf-8") != expected:
            target.write_text(expected, encoding="utf-8")
            written.append(f"{_slug(seat)}.md")

    # A seat removed from the registry must lose its agent, or the bench grows a reviewer
    # asking a question nobody registered any more -- the drift this compiler exists to stop,
    # running backwards.
    live = {f"{_slug(seat)}.md" for seat in seats}
    for orphan in AGENTS_DIR.glob(f"{PREFIX}*.md"):
        if orphan.name not in live:
            orphan.unlink()
            written.append(f"{orphan.name} (removed)")
    return sorted(written)


def main(argv: list[str] | None = None) -> int:
    args = list(sys.argv[1:] if argv is None else argv)
    seats = _load_seats()
    if "--write" in args:
        written = write()
        print(
            f"reviewers: {len(seats)} seat(s); wrote {len(written)}"
            + (f" ({', '.join(written)})" if written else " (all current)")
        )
        return 0

    stale = check()
    if stale:
        print(f"reviewers: {len(stale)} stale — {', '.join(stale)}")
        print("Run: py -m integrations.compiler.reviewers --write")
        return 1
    judgment = sum(
        1
        for lanes in seats.values()
        for lane in lanes
        if not lane.get("detector") and not lane.get("eval")
    )
    print(
        f"reviewers: all {len(seats)} seats match the registry "
        f"({judgment} judgment lane(s) now have a specialist to answer them)"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
