from __future__ import annotations

from .types_enum import EventCategory, EventType
from .types_meta import EventTypeMeta

_CORE_ENTRIES: tuple[EventTypeMeta, ...] = (
    # Hook-emitted types
    EventTypeMeta(
        EventType.SESSION_LIFECYCLE_STARTED,
        "telemetry",
        "Host AI session begun; session_id established",
        True,
        EventCategory.HOOK_EMITTED,
    ),
    EventTypeMeta(
        EventType.SESSION_LIFECYCLE_ENDED,
        "telemetry",
        "Host AI session ended normally",
        False,
        EventCategory.HOOK_EMITTED,
    ),
    EventTypeMeta(
        EventType.PROMPT_LIFECYCLE_SUBMITTED,
        "telemetry",
        "User submitted a prompt (redacted: no raw text)",
        True,
        EventCategory.HOOK_EMITTED,
    ),
    EventTypeMeta(
        EventType.PROMPT_LIFECYCLE_VALIDATED,
        "telemetry",
        "Prompt passed DS validation gates",
        False,
        EventCategory.HOOK_EMITTED,
    ),
    EventTypeMeta(
        EventType.TOOL_EXECUTION_STARTED,
        "telemetry",
        "A tool call began (tool name + args shape; no raw output)",
        False,
        EventCategory.HOOK_EMITTED,
    ),
    EventTypeMeta(
        EventType.TOOL_EXECUTION_COMPLETED,
        "telemetry",
        "A tool call completed (result shape; no raw output)",
        True,
        EventCategory.HOOK_EMITTED,
    ),
    EventTypeMeta(
        EventType.TOKEN_CONSUMPTION_RECORDED,
        "telemetry",
        "Token count for a session turn",
        True,
        EventCategory.HOOK_EMITTED,
    ),
    EventTypeMeta(
        EventType.SKILL_LIFECYCLE_LOADED,
        "telemetry",
        "A DS skill was activated for this session",
        False,
        EventCategory.HOOK_EMITTED,
    ),
    EventTypeMeta(
        EventType.SKILL_LIFECYCLE_COMPLETED,
        "telemetry",
        "A DS skill's primary action completed",
        False,
        EventCategory.HOOK_EMITTED,
    ),
    EventTypeMeta(
        EventType.WORKFLOW_PROGRESS_UPDATED,
        "telemetry",
        "A workflow milestone progressed",
        False,
        EventCategory.HOOK_EMITTED,
    ),
    EventTypeMeta(
        EventType.CONTEXT_THRESHOLD_CROSSED,
        "telemetry",
        "Context window crossed a configured threshold",
        True,
        EventCategory.HOOK_EMITTED,
    ),
    EventTypeMeta(
        EventType.SECURITY_SCAN_COMPLETED,
        "telemetry",
        "Security scan ran against a file or diff",
        False,
        EventCategory.HOOK_EMITTED,
    ),
    EventTypeMeta(
        EventType.QUALITY_SCORE_RECORDED,
        "telemetry",
        "Quality score computed for an artifact",
        False,
        EventCategory.HOOK_EMITTED,
    ),
    EventTypeMeta(
        EventType.INTEGRATION_HEALTH_CHANGED,
        "telemetry",
        "An integration health state transition occurred",
        False,
        EventCategory.HOOK_EMITTED,
    ),
    # Production-emitted types
    EventTypeMeta(
        EventType.GUARDRAIL_DECISION,
        "telemetry",
        "Guardrail policy decision logged for compliance audit",
        True,
        EventCategory.PRODUCTION_EMITTED,
    ),
    EventTypeMeta(
        EventType.RESEARCH_VALIDATED,
        "telemetry",
        "Research result validated by session outcome",
        True,
        EventCategory.PRODUCTION_EMITTED,
    ),
    EventTypeMeta(
        EventType.RESEARCH_COMPLETED,
        "telemetry",
        "Research query completed and result stored",
        True,
        EventCategory.PRODUCTION_EMITTED,
    ),
    EventTypeMeta(
        EventType.RESEARCH_CACHE_STORED,
        "telemetry",
        "Research result stored in cache",
        True,
        EventCategory.PRODUCTION_EMITTED,
    ),
    EventTypeMeta(
        EventType.RESEARCH_CACHE_CLEARED,
        "telemetry",
        "Research cache entry cleared for topic",
        True,
        EventCategory.PRODUCTION_EMITTED,
    ),
    EventTypeMeta(
        EventType.PROJECT_REGISTERED,
        "sdlc",
        "Project registered in the analysis registry",
        True,
        EventCategory.PRODUCTION_EMITTED,
    ),
    EventTypeMeta(
        EventType.PROJECT_UPDATED,
        "sdlc",
        "Project metadata updated in registry",
        True,
        EventCategory.PRODUCTION_EMITTED,
    ),
    EventTypeMeta(
        EventType.ANALYSIS_STARTED,
        "telemetry",
        "Project analysis pipeline started",
        True,
        EventCategory.PRODUCTION_EMITTED,
    ),
    EventTypeMeta(
        EventType.ANALYSIS_DISCOVERY_COMPLETED,
        "telemetry",
        "Discovery phase of analysis completed",
        True,
        EventCategory.PRODUCTION_EMITTED,
    ),
    EventTypeMeta(
        EventType.ANALYSIS_RESEARCH_COMPLETED,
        "telemetry",
        "Research phase of analysis completed",
        True,
        EventCategory.PRODUCTION_EMITTED,
    ),
    EventTypeMeta(
        EventType.ANALYSIS_AUDIT_COMPLETED,
        "telemetry",
        "Audit phase of analysis completed",
        True,
        EventCategory.PRODUCTION_EMITTED,
    ),
    EventTypeMeta(
        EventType.ANALYSIS_BUG_ANALYSIS_COMPLETED,
        "telemetry",
        "Bug analysis phase completed",
        True,
        EventCategory.PRODUCTION_EMITTED,
    ),
    EventTypeMeta(
        EventType.ANALYSIS_SYNTHESIS_COMPLETED,
        "telemetry",
        "Synthesis phase of analysis completed",
        True,
        EventCategory.PRODUCTION_EMITTED,
    ),
    EventTypeMeta(
        EventType.ANALYSIS_COMPLETED,
        "telemetry",
        "Full project analysis pipeline completed",
        True,
        EventCategory.PRODUCTION_EMITTED,
    ),
    EventTypeMeta(
        EventType.ANALYSIS_FAILED,
        "telemetry",
        "Project analysis pipeline failed",
        True,
        EventCategory.PRODUCTION_EMITTED,
    ),
    EventTypeMeta(
        EventType.AUDIT_VIOLATIONS_CLEARED,
        "telemetry",
        "Audit violations cleared before new scan",
        True,
        EventCategory.PRODUCTION_EMITTED,
    ),
    EventTypeMeta(
        EventType.AUDIT_VIOLATION_FOUND,
        "telemetry",
        "Architecture violation detected during audit",
        True,
        EventCategory.PRODUCTION_EMITTED,
    ),
    EventTypeMeta(
        EventType.AUDIT_IMPROVEMENTS_CLEARED,
        "telemetry",
        "Audit improvements cleared before new scan",
        True,
        EventCategory.PRODUCTION_EMITTED,
    ),
    EventTypeMeta(
        EventType.AUDIT_IMPROVEMENT_FOUND,
        "telemetry",
        "Architecture improvement opportunity detected",
        True,
        EventCategory.PRODUCTION_EMITTED,
    ),
    EventTypeMeta(
        EventType.REPO_ANALYZED,
        "telemetry",
        "External repository analysis completed",
        True,
        EventCategory.PRODUCTION_EMITTED,
    ),
    EventTypeMeta(
        EventType.REPO_EXTRACTION_STORED,
        "telemetry",
        "Repository pattern extraction stored",
        True,
        EventCategory.PRODUCTION_EMITTED,
    ),
    EventTypeMeta(
        EventType.EXECUTION_COMPLETE,
        "telemetry",
        "GitHub PR execution completed",
        True,
        EventCategory.PRODUCTION_EMITTED,
    ),
    EventTypeMeta(
        EventType.TESTS_EXECUTED,
        "telemetry",
        "Test suite executed and results collected",
        True,
        EventCategory.PRODUCTION_EMITTED,
    ),
    EventTypeMeta(
        EventType.WAVE_STARTED,
        "telemetry",
        "Execution wave started",
        True,
        EventCategory.PRODUCTION_EMITTED,
    ),
    EventTypeMeta(
        EventType.WAVE_COMPLETED,
        "telemetry",
        "Execution wave completed",
        True,
        EventCategory.PRODUCTION_EMITTED,
    ),
    EventTypeMeta(
        EventType.WAVE_FAILED,
        "telemetry",
        "Execution wave failed",
        True,
        EventCategory.PRODUCTION_EMITTED,
    ),
    EventTypeMeta(
        EventType.WAVE_TASK_UPDATED,
        "telemetry",
        "Wave task status updated",
        True,
        EventCategory.PRODUCTION_EMITTED,
    ),
    EventTypeMeta(
        EventType.WORKFLOW_LEARNED,
        "telemetry",
        "Workflow pattern learned from execution history",
        True,
        EventCategory.PRODUCTION_EMITTED,
    ),
    EventTypeMeta(
        EventType.DOCUMENT_CREATED,
        "sdlc",
        "Document created in document store",
        True,
        EventCategory.PRODUCTION_EMITTED,
    ),
    EventTypeMeta(
        EventType.DOCUMENT_UPDATED,
        "sdlc",
        "Document updated in document store",
        True,
        EventCategory.PRODUCTION_EMITTED,
    ),
    EventTypeMeta(
        EventType.DOCUMENT_ARCHIVED,
        "sdlc",
        "Document archived in document store",
        True,
        EventCategory.PRODUCTION_EMITTED,
    ),
    # CLI lifecycle events
    EventTypeMeta(
        EventType.WORK_ORDER_STARTED,
        "sdlc",
        "Work order entered in_progress state",
        True,
        EventCategory.PRODUCTION_EMITTED,
    ),
    EventTypeMeta(
        EventType.WORK_ORDER_CLOSED,
        "sdlc",
        "Work order closed after gate checks passed",
        True,
        EventCategory.PRODUCTION_EMITTED,
    ),
    EventTypeMeta(
        EventType.WORK_ORDER_BLOCKED,
        "sdlc",
        "Work order blocked with a stated reason",
        True,
        EventCategory.PRODUCTION_EMITTED,
    ),
    EventTypeMeta(
        EventType.GATE_BYPASSED,
        "sdlc",
        "A gate check was bypassed with --force",
        True,
        EventCategory.PRODUCTION_EMITTED,
    ),
    EventTypeMeta(
        EventType.TASK_COMPLETED,
        "sdlc",
        "A task within a work order was marked complete",
        True,
        EventCategory.PRODUCTION_EMITTED,
    ),
    EventTypeMeta(
        EventType.MILESTONE_COMPLETED,
        "sdlc",
        "A milestone was closed after verification",
        True,
        EventCategory.PRODUCTION_EMITTED,
    ),
    EventTypeMeta(
        EventType.SKILL_INVOKED,
        "sdlc",
        "A Dream Studio skill was invoked via CLI",
        True,
        EventCategory.PRODUCTION_EMITTED,
    ),
    EventTypeMeta(
        EventType.WORKFLOW_NODE_COMPLETED,
        "telemetry",
        "A workflow DAG node completed execution",
        True,
        EventCategory.PRODUCTION_EMITTED,
    ),
    EventTypeMeta(
        EventType.GATE_PRE_PUSH_FAILED,
        "sdlc",
        "A pre-push gate failed during `ds workflow run pre-push --non-interactive`",
        True,
        EventCategory.PRODUCTION_EMITTED,
    ),
)
