-- Migration 030: Adapter Metadata Tables
-- Created: 2026-05-06
-- Purpose: Support AI adapter layer execution tracking and normalization metadata
-- Part of: Track C (Control Plane) - AI Adapter Layer
-- Depends on: 017_activity_log.sql (activity_log table)

-- ============================================================================
-- ADAPTER EXECUTION TRACKING
-- ============================================================================

-- adapter_executions and its indexes removed in migration 128 (dead table; no live consumer).
-- DDL is retained as historical comment so existing test assertions remain readable.
--
-- Original DDL:
--   CREATE TABLE IF NOT EXISTS adapter_executions (
--       id INTEGER PRIMARY KEY AUTOINCREMENT,
--       activity_id INTEGER NOT NULL,
--       adapter_type TEXT NOT NULL,
--       normalized_at TEXT NOT NULL,
--       execution_time_ms REAL,
--       metadata TEXT,
--       FOREIGN KEY (activity_id) REFERENCES activity_log(activity_id) ON DELETE CASCADE
--   );
