-- Migration 058: TA0b — Domain field validation requirement
-- The canonical event trace JSON must include a "domain" field for all new events.
-- Domain values: "sdlc" | "telemetry" | "system"
-- - sdlc: work orders, tasks, milestones, projects, skills
-- - telemetry: token usage, tool execution, session lifecycle, execution runs
-- - system: infrastructure, internal Dream Studio events
--
-- No schema change required: trace is a JSON column. This migration
-- documents the requirement and registers the version for traceability.
-- Events emitted without domain will receive a stderr warning from the ingestor (TA0b).
-- Events without domain that predate this migration are backfilled in migration 060.
