-- Migration 090: Create guard_events table for runtime LLM guard operational telemetry.
--
-- Boundary with findings table:
--   findings — scan-time observations on files (rule fired on code, advisory result).
--             Written by on-skill-input hook per file match.
--   guard_events — runtime action decisions (memory skipped, injection logged, block
--                  decisions). Operational telemetry distinct from scan-findings.
--
-- Same project_id foreign key as findings; both queryable per project.
-- skill_scan_runs.scan_id links guard_events back to the scan that triggered them.

-- guard_events: dropped in migration 133 (all writers are test-only reachable).
--
-- Writers:
--   guardrails/delta_guard.py::_emit_delta_block_event() (line 129) — called only from
--     guard_delta_pairs(), which has zero production callers (no hook, CLI, or projection
--     imports it; only tests/unit/test_guard_phase3.py calls it).
--   guardrails/delta_guard.py::_emit_delta_advisory_events() (line 191) — same dead path.
--   guardrails/memory_taint.py::emit_memory_skip_event() (line 65) — called only from
--     tests/unit/test_guard_phase2.py; runtime/hooks/meta/on-memory-retrieve.py does NOT
--     import memory_taint.
--
-- Readers that gracefully degrade when table is absent:
--   projections/api/routes/guard_metrics.py — uses object_exists() guard, returns _guard_empty()
--   core/analytics/aggregate_metrics.py — guard_events queries wrapped in try/except
--   core/analytics/duckdb_store.py — guard_calibration DuckDB table kept (no studio.db dep)
