-- Migration 138: Drop the retired raw_token_usage SQLite table (WO 468ce225)
--
-- Target architecture: studio.db = canonical EVENTS + non-event-sourced AUTHORITY
-- + pipeline ONLY. raw_token_usage was a private direct-write telemetry table
-- (session_id, project_id, skill_name, input_tokens, output_tokens, model,
-- recorded_at) fed by one-time migration/backfill tooling. The signal it held
-- is really an event: the canonical token.consumed events in
-- ai_canonical_events/business_canonical_events are the complete, authoritative
-- source, and the DuckDB aggregate_metrics.db token_usage_records VIEW
-- (core/analytics/duckdb_store.py, widened in PR #450/#451 — see migration 137)
-- already serves every dashboard/API read this table used to back.
--
-- Evidence this table is safely droppable (operator duplication review,
-- 2026-07-03):
--   * Only 3 stale rows in the operator's authority — orders of magnitude
--     smaller than the 113-row token_usage_records table dropped in migration
--     137, and with no accounting fields (billing_mode, cost_visibility) at
--     all, unlike that table. Pure input/output token counts, fully covered
--     by token.consumed event payloads.
--   * No SQLite VIEW references raw_token_usage (grepped core/event_store/
--     migrations/ for CREATE VIEW bodies; none touch it).
--   * No FOREIGN KEY in any migration references raw_token_usage — unlike
--     token_usage_records (migration 137's ai_usage_operational_records.
--     token_usage_id FK), this drop needs no table-reconstruction rebuild.
--
-- Writers retired in this change set (all vestigial — reachable only from
-- one-time migration/backfill CLI tooling, never from a live hook, route, or
-- registered CLI command that a fresh install exercises):
--   core/event_store/studio_db.py::insert_token_usage — deleted (sole INSERT
--     target dropped below). get_token_summary() (sole SELECT reader, no
--     production caller — test-only) deleted alongside it.
--   interfaces/cli/migrate_to_db.py::_ingest_token_log — deleted (one-time
--     token-log.md → raw_token_usage ingest for the original file-to-SQLite
--     migration; call site in main() removed with it).
--   interfaces/cli/backfill_token_sessions.py::backfill_token_usage — deleted.
--     raw_sessions backfill (backfill_sessions()) is now this tool's sole
--     purpose; the two production callers that invoked backfill_token_usage()
--     (interfaces/cli/setup.py::step_analytics_bootstrap,
--     interfaces/cli/ds_dashboard.py::harvest_existing_data) were repointed to
--     call backfill_sessions() instead so first-run token-log.md harvesting
--     keeps working via the surviving function.
--
-- decision_records, eval_registry, ds_eval_baselines, and raw_sessions are NOT
-- touched by this migration — separate authority/registry tables and the
-- session-lifecycle read-write authority outside this change set (same note
-- migration 137 made when it left raw_token_usage untouched).
--
-- No FK references raw_token_usage anywhere in the migration chain, so no
-- table-reconstruction rebuild is needed (contrast migration 137's
-- ai_usage_operational_records rebuild for the token_usage_records FK).
--
-- Result: 75 - 1 = 74 tables.
-- Reviewed: 2026-07-03 (operator duplication review, WO 468ce225-795d-402f-af91-acf69ec78099)

DROP INDEX IF EXISTS idx_tokens_session;
DROP INDEX IF EXISTS idx_tokens_project_date;
DROP INDEX IF EXISTS idx_tokens_skill;
DROP TABLE IF EXISTS raw_token_usage;
