-- Migration 139: Collapse the AI per-type fact tables into the execution_events
-- spine (WO-AI-SPINE, work order a0cdd612-4c53-4cda-ab07-f940f8f814d5, AD-5)
--
-- Target architecture: studio.db = canonical EVENTS + non-event-sourced AUTHORITY
-- + pipeline ONLY. decision_records, outcome_records, and dashboard_attention_items
-- were per-type telemetry fact tables from migration 037's execution telemetry
-- traceability spine. Every writer of these three tables in
-- core/telemetry/emitters.py (emit_decision_record, emit_workflow_invocation,
-- emit_validation_result, emit_research_evidence_record, emit_security_finding)
-- ALREADY dual-writes an execution_events row describing the same fact
-- (event_type in 'decision.recorded' / 'workflow.invocation_recorded' /
-- 'validation.result_recorded' / 'security.finding_recorded', with
-- outcome_status carrying the per-fact status) — the per-type tables were pure
-- duplication of that write, not an independent signal.
--
-- Evidence this is safely droppable (operator duplication review, 2026-07-03,
-- operator-approved pre-squash removal 2026-07-03):
--   * decision_records: 0 rows in the operator's authority.
--   * outcome_records: 2 stale rows (both retired studio-onboard workflow runs
--     from 2026-05-18, already superseded).
--   * dashboard_attention_items: 0 rows in the operator's authority.
--   * No FOREIGN KEY in any migration references any of the three tables
--     (grepped core/event_store/migrations/ for "REFERENCES <table>("; the
--     only hits are each table's own migration-037 CREATE TABLE statement).
--     No table-reconstruction rebuild is needed (contrast migration 137's
--     ai_usage_operational_records rebuild for its token_usage_records FK).
--   * No SQLite VIEW references any of the three tables (grepped for CREATE
--     VIEW bodies; none touch them).
--
-- Writers removed (core/telemetry/emitters.py):
--   emit_decision_record — no longer INSERTs into decision_records; the
--     execution_events row (event_type='decision.recorded') is now the sole
--     write, using the stable decision_id directly as the execution_events
--     primary key (mirroring emit_workflow_invocation's existing idempotency
--     pattern) so duplicate calls remain a no-op without a decision_records
--     lookup.
--   emit_workflow_invocation, emit_decision_record — no longer call the
--     _record_outcome() helper (deleted) that INSERTed into outcome_records.
--   emit_validation_result — no longer INSERTs into outcome_records.
--   emit_validation_result, emit_workflow_invocation, emit_security_finding,
--     emit_research_evidence_record, emit_decision_record — no longer call
--     core/telemetry/execution_spine.py::record_dashboard_attention() (deleted)
--     to INSERT into dashboard_attention_items.
--   core/telemetry/execution_spine.py::record_dashboard_attention — deleted
--     (its sole purpose, the INSERT above, is gone).
--
-- Readers repointed (core/telemetry/read_models.py) to derive the same
-- dict/list shapes from execution_events, filtered by event_type +
-- outcome_status (see _DECISION_EVENTS_VIEW_SQL / _OUTCOME_EVENTS_VIEW_SQL /
-- _ATTENTION_EVENTS_VIEW_SQL): process_run_timeline's decisions/outcomes/
-- attention keys, workflow_execution_graph's outcomes key, _outcome_rollup,
-- _research_decision_rollup's decisions half, _attention_rollup,
-- _attention_groups, dashboard_attention_summary, and
-- _component_hardening_intelligence's outcome_count. Fields that were only
-- ever persisted on the dropped tables (decision selected_option/rationale;
-- outcome/attention summary; true attention title/severity for research and
-- decision events) are honestly NULL or best-effort derived — see the SQL
-- fragment comments in read_models.py. decision_records also appeared in
-- declaration lists across core/telemetry/execution_spine.py (DASHBOARD_MODULES),
-- core/telemetry/dashboard_freshness.py, core/shared_intelligence/
-- expert_workflows.py, core/shared_intelligence/scoped_agents.py,
-- core/upgrade/retention_policy.py, core/upgrade/installed_state_rehydration.py,
-- and core/module_contracts.py — all updated to remove the three names.
--
-- Result: 65 - 3 = 62 tables (fresh bootstrap_database() count of
-- sqlite_master tables excluding sqlite_%, measured 2026-07-04).
-- Reviewed: 2026-07-04 (WO-AI-SPINE, work order a0cdd612-4c53-4cda-ab07-f940f8f814d5)

DROP TABLE IF EXISTS decision_records;
DROP TABLE IF EXISTS outcome_records;
DROP TABLE IF EXISTS dashboard_attention_items;
