"""Tombstone registry: studio.db tables intentionally dropped by the migration
chain that must NEVER resurface (operator directive, 2026-07-03, WO-TOMBSTONE-GUARD).

Generated from every comment-stripped DROP TABLE statement across
core/event_store/migrations/, minus names present in a fresh fully-migrated
schema (legitimate rebuild patterns like the migration-081/137 table
reconstructions survive and are therefore not tombstones).

When a future migration intentionally drops a table, regenerate or append here
in the SAME change set — test_schema_tombstones.py pins this list against the
chain. When a future migration intentionally REVIVES a name (should be never;
pick a new name instead), it must be removed here with an operator-approved
rationale in the commit body.
"""

from __future__ import annotations

# Table names that legitimately appear in production CREATE statements even
# though they are tombstoned for studio.db — each with the reason.
TOMBSTONE_CREATOR_EXCEPTIONS: dict[str, str] = {
    # Dropped from studio.db (migration 127) but alive in files.db, created by
    # core/storage/document_store.py / core/files/store.py against
    # ~/.dream-studio/state/files.db — a different database.
    "ds_documents": "lives in files.db (never-authority docstore), not studio.db",
    "ds_documents_fts": "FTS index of ds_documents in files.db, not studio.db",
}

TOMBSTONED_TABLES: frozenset[str] = frozenset(
    {
        "activity_log",
        "adapter_executions",
        "adapter_result_records",
        "agent_context_scope_policies",
        "agent_invocations",
        "agent_registry_records",
        "agent_result_records",
        "alert_history",
        "artifact_authority_records",
        "artifact_records",
        "audit_runs",
        "authority_projection_records",
        "automation_checkpoints",
        "automation_log",
        "blocker_resolution_records",
        "business_work_order_preflights",
        "canonical_events_legacy_backup",
        "capability_center_records",
        "capability_route_records",
        "career_application_events",
        "career_application_field_mappings",
        "career_applications",
        "career_browser_automation_runs",
        "career_case_studies",
        "career_cover_letter_versions",
        "career_evidence_refs",
        "career_interview_story_bank",
        "career_job_opportunities",
        "career_portfolio_artifacts",
        "career_profile_fields",
        "career_profiles",
        "career_resume_versions",
        "career_role_targets",
        "career_scorecards",
        "compliance_review_flags",
        "connector_ingestion_runs",
        "cor_skill_corrections",
        "dashboard_attention_items",
        "dashboard_authority_reconciliation_records",
        "decision_event_link",
        "decision_log",
        "decision_records",
        "demo_case_study_packets",
        "ds_design_briefs",
        "ds_documents",
        "ds_documents_fts",
        "ds_eval_runs",
        "ds_milestones",
        "ds_projects",
        "ds_tasks",
        "ds_technology_signals",
        "ds_work_order_types",
        "ds_work_orders",
        "execution_dependencies",
        "execution_event_links",
        "execution_nodes",
        "execution_outputs",
        "findings",
        "findings_current_status",
        "github_repo_adoption_decisions",
        "github_repo_attribution_records",
        "github_repo_dependency_findings",
        "github_repo_evaluations",
        "github_repo_integration_candidates",
        "github_repo_license_findings",
        "github_repo_pattern_references",
        "github_repo_security_findings",
        "guard_events",
        "guardrail_rules_audit",
        "hardening_candidate_records",
        "hook_eval_runs",
        "hook_executions",
        "hook_executions_new",
        "hook_findings",
        "hook_findings_new",
        "hook_invocations",
        "installer_distribution_checks",
        "learning_event_records",
        "legacy_canonical_event_import_map",
        "local_watch_schedule_records",
        "model_provider_profiles",
        "outcome_records",
        "pending_audits",
        "pi_analysis_runs",
        "pi_bugs",
        "pi_components",
        "pi_dependencies",
        "pi_improvements",
        "pi_violations",
        "pi_wave_tasks",
        "pi_waves",
        "policy_decision_records",
        "prd_amendment_records",
        "prd_assumptions",
        "prd_change_orders",
        "prd_documents",
        "prd_handoffs",
        "prd_intake_questions",
        "prd_intakes",
        "prd_notes",
        "prd_plans",
        "prd_requirements",
        "prd_route_reconciliation_records",
        "prd_sessions",
        "prd_specs",
        "prd_tasks",
        "prd_version_records",
        "preflight_events",
        "privacy_redaction_export_records",
        "process_runs",
        "production_readiness_assessment_runs",
        "production_readiness_control_results",
        "production_readiness_findings",
        "production_readiness_remediation_work_orders",
        "production_readiness_skill_control_mappings",
        "proj_decision_patterns",
        "proj_security_summary",
        "proj_sessions",
        "proj_skill_stats",
        "proj_workflow_runs",
        "project_assumption_records",
        "project_change_order_records",
        "project_health_scorecards",
        "project_intake_questions",
        "project_intake_records",
        "project_milestone_records",
        "project_readiness_scorecards",
        "project_work_order_authority_records",
        "raw_planning_specs",
        "raw_pulse_snapshots",
        "raw_research",
        "raw_research_temp",
        "raw_specs",
        "raw_tasks",
        "raw_token_usage",
        "raw_workflow_nodes",
        "raw_workflow_nodes_bak071",
        "raw_workflow_nodes_temp",
        "raw_workflow_runs",
        "raw_workflow_runs_bak071",
        "raw_workflow_runs_temp",
        "reg_analyzed_repos",
        "reg_projects",
        "reg_repo_extractions",
        "reg_repo_research_links",
        "reg_research_sources",
        "reg_skill_deps",
        "reg_skills",
        "reg_workflows",
        "release_readiness_records",
        "research_cache_temp",
        "resolved_finding_links",
        "risk_mitigations",
        "risk_register",
        "route_decision_records",
        "scan_deltas",
        "sec_cve_matches",
        "sec_cve_matches_new",
        "sec_hook_checks",
        "sec_hook_checks_new",
        "sec_manual_reviews",
        "sec_manual_reviews_new",
        "sec_sarif_findings",
        "sec_sarif_findings_new",
        "session_tasks",
        "shared_context_packets",
        "skill_evaluation_runs",
        "skill_invocations",
        "sum_analytics_run",
        "sum_skill_summary",
        "task_attribution_records",
        "team_rollup_records",
        "telemetry_entity_registry",
        "telemetry_module_registry",
        "temp_fk_constraint",
        "token_usage_records",
        "tool_embeddings_cache",
        "tool_invocations",
        "tool_registry",
        "validation_failures",
        "workflow_agent_skill_mappings",
        "workflow_invocations",
    }
)
