"""Generated by WO-SQUASH-AUDIT — authoritative keep/drop/resurface classification.

DROP = remove in the lean baseline; KEEP = carry into 001_baseline.sql;
RESURFACE = dormant feature surface, operator decides keep-or-drop at approval.

The human-readable audit (row counts, writers, readers, source migration, deps)
lives in .planning/audits/schema-keeplist.md. This module is the machine-readable
slice the gate tests in test_schema_keep_list.py consume; keep the two in sync.
"""

from __future__ import annotations

# Tables created at runtime by live (non-migration) code — absent from a freshly
# bootstrapped schema but present in the live authority.
RUNTIME_TABLES = {
    "projection_checkpoints",  # core/projections/framework.py
    # validation_failures removed: dropped in migration 129 (WO-READMODELS-DUCKDB);
    # DuckDB validation_failures VIEW replaces the SQLite projection table.
}

CLASSIFICATION: dict[str, str] = {
    "_schema_version": "KEEP",
    "adapter_authority_profiles": "KEEP",
    "adapter_executions": "DROP",
    "adapter_result_records": "DROP",  # Dropped migration 131: dead writer record_adapter_result(), never called from production
    "ai_adapter_accounting_profiles": "KEEP",
    "ai_canonical_events": "KEEP",
    "ai_usage_operational_records": "KEEP",  # LIVE writer: analytics_ingestion.ingest_analytics_payload() via `ds system analytics-ingest`; indexes managed by migrations 081/117
    "alert_history": "DROP",  # Dropped migration 131: dead writer trigger_alert(), AlertEvaluator never instantiated in production
    "alert_rules": "KEEP",
    "artifact_authority_records": "DROP",  # Dropped migration 131: dead writer record_artifact_authority(), test-only callers
    "artifact_records": "DROP",  # Dropped migration 130: 0 rows, no production writer, aspirational telemetry
    "audit_runs": "DROP",  # Dropped migration 149 (WO-SCHEMALEAN): 0 rows, no internal writer since the initial commit (external-write API endpoint nothing in-repo ever calls); routes referenced already-dropped sec_sarif_findings/sec_cve_matches. Superseded by the live /api/v1/security/* surface (security_events + scan_runs).
    "authority_projection_records": "DROP",  # Dropped migration 130: 0 rows, no live writer, aspirational telemetry
    "blocker_resolution_records": "DROP",  # Dropped migration 130: 0 rows, no live writer, aspirational telemetry
    "business_canonical_events": "KEEP",
    "business_design_briefs": "KEEP",
    "business_milestones": "KEEP",
    "business_projects": "KEEP",
    "business_tasks": "KEEP",
    "business_work_order_artifacts": "KEEP",  # Added migration 144 (WO-FILESDB-P1): WO ceremony artifacts moved off .planning disk into the authority
    "business_work_order_preflights": "DROP",  # Dropped migration 148 (WO-SCHEMALEAN): read model of the unwired preflight stack (0 rows, no live writer — PreflightProjection folds the empty preflight_events); start-gate reader removed. Duplicative of the live CI blast-radius gate.
    "business_work_order_types": "KEEP",
    "business_work_orders": "KEEP",
    "canonical_events_legacy_backup": "DROP",
    "capability_route_records": "DROP",  # Dropped migration 147 (WO-SCHEMALEAN): persist=False dead gate — record_capability_route only reachable when recommend_capability_route(persist=True), which no production caller passes (same pattern as compliance_review_flags); recommendation preview kept
    "compliance_review_flags": "DROP",  # Dropped migration 133: persist=False dead gate — _record_compliance_flags() only reachable when persist=True, which no production caller passes
    "connector_ingestion_runs": "DROP",  # Dropped migration 131: dead writer ingest_connector_payload(), test-only callers
    "cor_skill_corrections": "DROP",  # Dropped migration 131: dead writer skill_correct(), only reachable via unregistered __main__
    "dashboard_attention_items": "DROP",  # Dropped migration 139 (WO-AI-SPINE, AD-5): 0 production rows; record_dashboard_attention() writer removed — pure duplication of the execution_events row each caller already wrote
    "decision_event_link": "DROP",  # Dropped migration 136: emit_decision's decision.recorded canonical event is the sole durable write; join replaced by payload.triggered_event_id
    "decision_log": "DROP",  # Dropped migration 136: writer emit_decision() repointed to decision.recorded canonical events; readers repointed to business_canonical_events
    "decision_records": "DROP",  # Dropped migration 139 (WO-AI-SPINE, AD-5): 0 production rows; emit_decision_record() no longer writes it — pure duplication of the execution_events row it already wrote
    "demo_case_study_packets": "DROP",
    "ds_config": "KEEP",
    # ds_documents cluster removed from classification: migration 127 dropped
    # these tables from studio.db.  They now live in files.db (three-store arch).
    "ds_escalations": "KEEP",
    "ds_eval_baselines": "KEEP",
    "ds_eval_runs": "DROP",  # Dropped migration 136: writers (verify.py, eval/runner.py) repointed to work_order.verified/eval.run.completed canonical events
    "ds_friction_signals": "KEEP",
    "ds_technology_signals": "DROP",  # Dropped migration 132: pure write-only sink, zero production readers
    "ds_user_extensions": "KEEP",
    "ds_workflow_pattern_signals": "KEEP",
    "eval_registry": "KEEP",
    "execution_dependencies": "DROP",  # Dropped migration 131: dead writer add_dependency(), dream_exec.py unregistered from ds CLI
    "execution_event_links": "DROP",  # Dropped migration 131: dead writer link_event_to_node(), dream_exec.py unregistered from ds CLI
    "execution_events": "KEEP",
    "execution_nodes": "DROP",  # Dropped migration 131: dead writer create_node(), dream_exec.py unregistered from ds CLI
    "execution_outputs": "DROP",  # Dropped migration 131: dead writer add_output(), dream_exec.py unregistered from ds CLI
    "findings_current_status": "DROP",  # Dropped migration 140 (WO dff23cb0): derived status projection over security/readiness events; readers now derive current status from the events directly
    "fts_gotchas": "KEEP",
    "fts_gotchas_config": "KEEP",
    "fts_gotchas_data": "KEEP",
    "fts_gotchas_docsize": "KEEP",
    "fts_gotchas_idx": "KEEP",
    "github_repo_adoption_decisions": "DROP",  # Dropped migration 131: dead writer record_github_repo_evaluation(), never called from production
    "github_repo_attribution_records": "DROP",
    "github_repo_dependency_findings": "DROP",
    "github_repo_evaluations": "DROP",  # Dropped migration 131: dead writer record_github_repo_evaluation(), never called from production
    "github_repo_integration_candidates": "DROP",
    "github_repo_license_findings": "DROP",
    "github_repo_pattern_references": "DROP",
    "github_repo_security_findings": "DROP",
    "guard_events": "DROP",  # Dropped migration 133: all writers (delta_guard.py, memory_taint.py) are test-only reachable; no hook/CLI/projection calls them
    "guardrail_decisions": "KEEP",
    "hardening_candidate_records": "DROP",  # Dropped migration 131: dead writer record_hardening_candidate(), test-only callers
    "hook_eval_runs": "DROP",  # Dropped migration 136: writer guardrails/evaluator.py::_write_hook_eval_run() repointed to eval.run.completed canonical events
    "hook_executions": "DROP",  # Dropped mig 129: DuckDB hook_executions VIEW (over
    #                             system.hook.execution.logged) replaces it; writer now only
    #                             emits the canonical event; all reads repointed to DuckDB.
    "hook_findings": "DROP",  # Dropped migration 130: 0 rows, no live readers, writer removed
    "installer_distribution_checks": "DROP",
    "learning_event_records": "DROP",  # Dropped migration 131: dead writer record_learning_event(), test-only callers
    "legacy_canonical_event_import_map": "DROP",
    "local_watch_schedule_records": "DROP",
    "log_batch_imports": "KEEP",
    "memory_entries": "KEEP",
    "memory_fts": "KEEP",
    "memory_fts_config": "KEEP",
    "memory_fts_content": "KEEP",
    "memory_fts_data": "KEEP",
    "memory_fts_docsize": "KEEP",
    "memory_fts_idx": "KEEP",
    "model_provider_profiles": "DROP",  # Dropped migration 131: dead writer record_model_provider_profile(), test-only callers
    "outcome_records": "DROP",  # Dropped migration 139 (WO-AI-SPINE, AD-5): 2 stale rows (retired studio-onboard runs); _record_outcome() writer removed — pure duplication of the execution_events row each caller already wrote
    "pending_audits": "DROP",  # Dropped migration 131: dead writer defer_project_audit(), never called from any production path
    "policy_decision_records": "DROP",  # Dropped migration 133: test-only writer record_policy_decision(); no production CLI/hook/route calls it
    "preflight_events": "DROP",  # Dropped migration 148 (WO-SCHEMALEAN): spine of the unwired preflight stack (0 rows); only writer create_preflight is called solely by the never-wired spec_ingestor.ingest_specs. Duplicative of the live CI blast-radius gate.
    "privacy_redaction_export_records": "DROP",
    "process_runs": "DROP",  # Dropped migration 131: dead writer record_process_run(), test-only callers
    "projection_checkpoints": "KEEP",
    "projection_dead_letter": "KEEP",
    "projection_retry_queue": "KEEP",
    "projection_state": "KEEP",
    "raw_approaches": "KEEP",
    "raw_claude_code_events": "KEEP",
    "raw_handoffs": "KEEP",
    "raw_lessons": "KEEP",
    "raw_operational_snapshots": "KEEP",
    "raw_planning_specs": "DROP",
    "raw_pulse_snapshots": "DROP",
    "raw_research": "DROP",  # Dropped migration 131: dead writers insert_research()/_store_research(), test-only callers
    "raw_runtime_state": "KEEP",  # Added migration 146 (WO-FILESDB-P2): active_skill/active_task/platform singleton JSON moved off ~/.dream-studio/state/*.json into key->JSON rows
    "raw_session_token_accumulators": "KEEP",  # Added migration 145 (WO-FILESDB-P2): per-session token running totals moved off session-tokens-<sid>.json disk files
    "raw_sentinels": "KEEP",
    "raw_sessions": "KEEP",  # Read-WRITE session-lifecycle authority, NOT a read-model:
    #                          end_session() UPDATEs ended_at/duration_s/outcome; record_session()
    #                          INSERTs; mark_handoff_consumed() UPDATEs handoff_consumed (a mutable
    #                          flag with NO canonical-event source). resume_from_handoff.py reads
    #                          handoff_consumed to prevent handoff re-spawn. (DuckDB has a derived
    #                          read VIEW for dashboards, but it cannot back the writes/flag.)
    "raw_skill_telemetry": "KEEP",
    "raw_specs": "DROP",
    "raw_tasks": "DROP",
    "raw_token_usage": "DROP",  # Dropped migration 138 (WO 468ce225): 3 stale rows, no
    #                             accounting fields, no FK/view references. Superseded by
    #                             canonical token.consumed events + the DuckDB
    #                             aggregate_metrics.db token_usage_records view. Writers
    #                             removed: studio_db.insert_token_usage, migrate_to_db.py
    #                             ::_ingest_token_log, backfill_token_sessions.py
    #                             ::backfill_token_usage.
    "raw_workflow_nodes": "DROP",  # Dropped migration 141 (WO 9f47a1a0): write-orphaned since 2026-05-18 — archive_workflow() silently failed; replaced by spool-emitted workflow.node.completed canonical events
    "raw_workflow_runs": "DROP",  # Dropped migration 141 (WO 9f47a1a0): write-orphaned since 2026-05-18 — archive_workflow() silently failed; replaced by spool-emitted workflow.completed canonical events
    "readiness_events": "KEEP",
    "reg_analyzed_repos": "DROP",
    "reg_gotchas": "KEEP",
    "reg_repo_extractions": "DROP",
    "reg_research_sources": "DROP",
    "reg_skill_deps": "DROP",
    "reg_skills": "DROP",
    "reg_workflows": "DROP",
    "release_readiness_records": "DROP",  # Dropped migration 133: same persist=False dead gate as compliance_review_flags; _record_scorecards() unreachable in production
    "research_cache": "KEEP",
    "research_evidence_records": "KEEP",
    "route_decision_records": "DROP",  # Dropped migration 131: dead writer emit_route_decision() via handoff.py, no live callers
    "scan_runs": "KEEP",
    "security_events": "KEEP",
    "shared_context_packets": "DROP",  # Dropped migration 131: writer record_shared_context_packet() exists but all callers use persist=False
    "skill_evaluation_runs": "DROP",  # Dropped migration 131: dead writer record_skill_evaluation(), test-only callers
    "sum_analytics_run": "DROP",
    "sum_skill_summary": "DROP",  # Dropped migration 140 (WO dff23cb0): derived rebuild_summaries() rollup over raw_skill_telemetry; get_skill_summaries() now computes the same aggregation live
    "task_attribution_records": "DROP",  # Dropped migration 131: dead writer record_task_attribution(), test-only callers
    "team_rollup_records": "DROP",
    "token_usage_records": "DROP",  # Dropped migration 137 (WO-DBA-DROP): all 113 live rows had
    #                                 billing_mode='unknown', cost_visibility='unknown',
    #                                 estimated_cost=0.0 — degenerate accounting columns, no
    #                                 information beyond the canonical token.consumed event stream.
    #                                 PR #450/#451 widened the DuckDB aggregate_metrics.db
    #                                 token_usage_records VIEW to derive model_id, cached_tokens,
    #                                 cache_read_tokens, and estimated_cost (LEFT JOIN
    #                                 token_model_pricing) from events_fact — the gap that made
    #                                 this table "KEEP" at migration 136 no longer exists. Readers
    #                                 (dashboard_truth gate, token_collector, cost_analysis,
    #                                 read_models rollups, usage_accounting) repointed to the view.
    "tool_embeddings_cache": "DROP",  # Dropped migration 131: dead writer build_embedding_index(), never called from live path
    "tool_registry": "DROP",  # Dropped migration 131: no production INSERT exists, only test fixtures
    "validation_failures": "DROP",  # Dropped mig 129: DuckDB validation_failures VIEW replaces it
    "validation_results": "KEEP",
    "work_order_dependencies": "KEEP",
}
