"""WO-P20-AGENTS-GEN: AGENTS.md generator + CLAUDE.md @AGENTS.md import + drift gate.

AGENTS.md is the generated, tool-agnostic universal target. CLAUDE.md reduces to a
Claude adapter that imports it, so routing/gate content lives in exactly one place,
and a drift gate flags a stale committed AGENTS.md.
"""

from __future__ import annotations

import tempfile
from pathlib import Path

from integrations.compiler.agents_md import (
    build_agents_md,
    build_repo_agents_md,
    check_agents_md_fresh,
    write_agents_md,
)

REPO_ROOT = Path(__file__).resolve().parents[2]


def test_the_repo_file_carries_contributor_guidance_not_routing():
    """The committed AGENTS.md is read by an agent working ON this repo.

    It carried the routing table, work-order types and close gates until
    2026-09-21. Nobody installing Dream Studio ever reads it -- `dist/plugin`
    ships neither this nor CLAUDE.md -- so with the product installed that content
    duplicated the operator projection and drifted from it, and without it
    installed it routed every session at skills, an authority database and hooks
    that were not there. Which is what happened after an uninstall: the file
    survived because it is checked into git.
    """
    content = build_repo_agents_md()

    assert "## Skill Routing" not in content
    assert "| Pack | Skill | Mode keywords |" not in content
    assert "## Work Order Types" not in content
    assert "## Gate Definitions" not in content

    # What it does carry: how to work on the codebase.
    assert "## Running tests" in content
    assert "py -m core.gates.pre_push" in content
    assert "GENERATED by integrations/compiler/agents_md.py" in content


def test_generates_valid_agents_md_with_routing():
    """T1: the generator emits a valid AGENTS.md with the real routing table,
    work-order types, and gate definitions.

    This is the OPERATOR projection the installer ships, not the repo-root file.
    An install whose skills are present with nothing routing to them does nothing,
    so this content must survive any trimming of the contributor copy -- the two
    were one function until 2026-09-21, and collapsing them stripped routing out
    of every fresh install.
    """
    content = build_agents_md()

    # Routing table is real (driven by packs.yaml + canonical skill metadata).
    assert "## Skill Routing" in content
    assert "Pack-Based Routing" in content
    assert "| Pack | Skill | Mode keywords |" in content
    assert "`ds-core`" in content and "`ds-quality`" in content

    # Work-order types section — the canonical 10-type set.
    assert "## Work Order Types" in content
    for wo_type in ("ui_component", "api_endpoint", "data_pipeline", "documentation"):
        assert f"`{wo_type}`" in content, f"WO type {wo_type} missing"

    # Gate definitions section.
    assert "## Gate Definitions" in content
    for gate in ("tasks_done", "design_brief_locked", "independent_review"):
        assert f"`{gate}`" in content, f"gate {gate} missing"

    # Generated marker present (so humans know not to hand-edit).
    assert "GENERATED by integrations/compiler/agents_md.py" in content


def test_claude_md_imports_agents_md_no_dup():
    """T2: CLAUDE.md imports @AGENTS.md and does NOT duplicate the routing table."""
    from integrations.compiler.claude_code import compile_pack

    # Compiler output (the installed CLAUDE.md).
    pack = compile_pack()
    claude_md = pack["files"]["CLAUDE.md"]
    assert "@AGENTS.md" in claude_md, "compiled CLAUDE.md must import @AGENTS.md"
    assert (
        "| Pack | Skill | Mode keywords |" not in claude_md
    ), "routing table must not be duplicated"
    assert "AGENTS.md" in pack["files"], "compiler must ship AGENTS.md for the import to resolve"

    # THE REPO-ROOT CLAUDE.md IS A DIFFERENT FILE WITH A DIFFERENT JOB. It used to
    # import @AGENTS.md too, which is how the operator routing table reached every
    # session opened in this repository -- including sessions with Dream Studio
    # uninstalled, where it named 13 skills, an authority database and blocking
    # hooks that did not exist. It now carries contributor guidance and imports
    # nothing.
    repo_claude = (REPO_ROOT / "CLAUDE.md").read_text(encoding="utf-8")
    assert "@AGENTS.md" not in repo_claude, (
        "the repo-root CLAUDE.md must not import the operator routing table --"
        " it is read by contributors, not by anyone running the product"
    )
    assert "| Pack | Skill | Mode keywords |" not in repo_claude
    assert "Contributor Instructions" in repo_claude


def test_stale_agents_md_is_flagged():
    """T3: the drift check flags a missing or stale AGENTS.md and passes when fresh."""
    with tempfile.TemporaryDirectory() as td:
        path = Path(td) / "AGENTS.md"

        # Missing → flagged.
        missing = check_agents_md_fresh(path)
        assert missing["ok"] is False and missing["exists"] is False

        # Stale (wrong content) → flagged.
        path.write_text("# hand-edited stale AGENTS.md\n", encoding="utf-8")
        stale = check_agents_md_fresh(path)
        assert stale["ok"] is False and stale["stale"] is True

        # Freshly generated → passes. The REPO builder, because that is what the
        # committed file is and what check_agents_md_fresh compares against;
        # writing the operator projection here would report a correct file stale.
        path.write_text(build_repo_agents_md(), encoding="utf-8")
        fresh = check_agents_md_fresh(path)
        assert fresh["ok"] is True and fresh["stale"] is False


def test_end_to_end():
    """T4: generate → check-fresh passes; drift → flagged; committed AGENTS.md current."""
    with tempfile.TemporaryDirectory() as td:
        path = Path(td) / "AGENTS.md"
        written = write_agents_md(path)
        assert written == path and path.is_file()
        assert check_agents_md_fresh(path)["ok"] is True

        # Introduce drift → flagged.
        path.write_text(path.read_text(encoding="utf-8") + "\n<!-- drift -->\n", encoding="utf-8")
        assert check_agents_md_fresh(path)["ok"] is False

    # The committed repo-root AGENTS.md must itself be current (drift gate green).
    assert check_agents_md_fresh(REPO_ROOT / "AGENTS.md")["ok"] is True
